//
// FirmwareAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class FirmwareAPI {

    /**
     Add Firmware
     
     - parameter platformId: (query)  
     - parameter files: (form)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func addFirmwareApiFirmwarePost(platformId: Int, files: [URL], apiResponseQueue: DispatchQueue = RommAPIAPI.apiResponseQueue, completion: @escaping ((_ data: AddFirmwareResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return addFirmwareApiFirmwarePostWithRequestBuilder(platformId: platformId, files: files).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Add Firmware
     - POST /api/firmware
     - Upload firmware files endpoint  Args:     request (Request): Fastapi Request object     platform_slug (str): Slug of the platform where to upload the files     files (list[UploadFile], optional): List of files to upload  Raises:     HTTPException  Returns:     AddFirmwareResponse: Standard message response
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - parameter platformId: (query)  
     - parameter files: (form)  
     - returns: RequestBuilder<AddFirmwareResponse> 
     */
    open class func addFirmwareApiFirmwarePostWithRequestBuilder(platformId: Int, files: [URL]) -> RequestBuilder<AddFirmwareResponse> {
        let localVariablePath = "/api/firmware"
        let localVariableURLString = RommAPIAPI.basePath + localVariablePath
        let localVariableFormParams: [String: Any?] = [
            "files": files.encodeToJSON(),
        ]

        let localVariableNonNullParameters = APIHelper.rejectNil(localVariableFormParams)
        let localVariableParameters = APIHelper.convertBoolToString(localVariableNonNullParameters)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "platform_id": (wrappedValue: platformId.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "multipart/form-data",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AddFirmwareResponse>.Type = RommAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Delete Firmware
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func deleteFirmwareApiFirmwareDeletePost(apiResponseQueue: DispatchQueue = RommAPIAPI.apiResponseQueue, completion: @escaping ((_ data: MessageResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return deleteFirmwareApiFirmwareDeletePostWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Delete Firmware
     - POST /api/firmware/delete
     - Delete firmware endpoint  Args:     request (Request): Fastapi Request object.         {             \"firmware\": List of firmware IDs to delete         }     delete_from_fs (bool, optional): Flag to delete rom from filesystem. Defaults to False.  Returns:     MessageResponse: Standard message response
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - returns: RequestBuilder<MessageResponse> 
     */
    open class func deleteFirmwareApiFirmwareDeletePostWithRequestBuilder() -> RequestBuilder<MessageResponse> {
        let localVariablePath = "/api/firmware/delete"
        let localVariableURLString = RommAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<MessageResponse>.Type = RommAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get Firmware
     
     - parameter id: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getFirmwareApiFirmwareIdGet(id: Int, apiResponseQueue: DispatchQueue = RommAPIAPI.apiResponseQueue, completion: @escaping ((_ data: FirmwareSchema?, _ error: Error?) -> Void)) -> RequestTask {
        return getFirmwareApiFirmwareIdGetWithRequestBuilder(id: id).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get Firmware
     - GET /api/firmware/{id}
     - Get firmware endpoint  Args:     request (Request): Fastapi Request object     id (int): Firmware internal id  Returns:     FirmwareSchema: Firmware stored in the database
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - parameter id: (path)  
     - returns: RequestBuilder<FirmwareSchema> 
     */
    open class func getFirmwareApiFirmwareIdGetWithRequestBuilder(id: Int) -> RequestBuilder<FirmwareSchema> {
        var localVariablePath = "/api/firmware/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = RommAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<FirmwareSchema>.Type = RommAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get Firmware Content
     
     - parameter id: (path)  
     - parameter fileName: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getFirmwareContentApiFirmwareIdContentFileNameGet(id: Int, fileName: String, apiResponseQueue: DispatchQueue = RommAPIAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return getFirmwareContentApiFirmwareIdContentFileNameGetWithRequestBuilder(id: id, fileName: fileName).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get Firmware Content
     - GET /api/firmware/{id}/content/{file_name}
     - Download firmware endpoint  Args:     request (Request): Fastapi Request object     id (int): Rom internal id     file_name (str): Required due to a bug in emulatorjs  Returns:     FileResponse: Returns the firmware file
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - parameter id: (path)  
     - parameter fileName: (path)  
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func getFirmwareContentApiFirmwareIdContentFileNameGetWithRequestBuilder(id: Int, fileName: String) -> RequestBuilder<AnyCodable> {
        var localVariablePath = "/api/firmware/{id}/content/{file_name}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let fileNamePreEscape = "\(APIHelper.mapValueToPathItem(fileName))"
        let fileNamePostEscape = fileNamePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{file_name}", with: fileNamePostEscape, options: .literal, range: nil)
        let localVariableURLString = RommAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = RommAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get Platform Firmware
     
     - parameter platformId: (query)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getPlatformFirmwareApiFirmwareGet(platformId: Int? = nil, apiResponseQueue: DispatchQueue = RommAPIAPI.apiResponseQueue, completion: @escaping ((_ data: [FirmwareSchema]?, _ error: Error?) -> Void)) -> RequestTask {
        return getPlatformFirmwareApiFirmwareGetWithRequestBuilder(platformId: platformId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get Platform Firmware
     - GET /api/firmware
     - Get firmware endpoint  Args:     request (Request): Fastapi Request object  Returns:     list[FirmwareSchema]: Firmware stored in the database
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - parameter platformId: (query)  (optional)
     - returns: RequestBuilder<[FirmwareSchema]> 
     */
    open class func getPlatformFirmwareApiFirmwareGetWithRequestBuilder(platformId: Int? = nil) -> RequestBuilder<[FirmwareSchema]> {
        let localVariablePath = "/api/firmware"
        let localVariableURLString = RommAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "platform_id": (wrappedValue: platformId?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[FirmwareSchema]>.Type = RommAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Head Firmware Content
     
     - parameter id: (path)  
     - parameter fileName: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func headFirmwareContentApiFirmwareIdContentFileNameHead(id: Int, fileName: String, apiResponseQueue: DispatchQueue = RommAPIAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return headFirmwareContentApiFirmwareIdContentFileNameHeadWithRequestBuilder(id: id, fileName: fileName).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Head Firmware Content
     - HEAD /api/firmware/{id}/content/{file_name}
     - Head firmware content endpoint  Args:     request (Request): Fastapi Request object     id (int): Rom internal id     file_name (str): Required due to a bug in emulatorjs  Returns:     FileResponse: Returns the response with headers
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - parameter id: (path)  
     - parameter fileName: (path)  
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func headFirmwareContentApiFirmwareIdContentFileNameHeadWithRequestBuilder(id: Int, fileName: String) -> RequestBuilder<AnyCodable> {
        var localVariablePath = "/api/firmware/{id}/content/{file_name}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let fileNamePreEscape = "\(APIHelper.mapValueToPathItem(fileName))"
        let fileNamePostEscape = fileNamePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{file_name}", with: fileNamePostEscape, options: .literal, range: nil)
        let localVariableURLString = RommAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = RommAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "HEAD", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
