//
// PlatformsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class PlatformsAPI {

    /**
     Add Platform
     
     - parameter bodyAddPlatformApiPlatformsPost: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func addPlatformApiPlatformsPost(bodyAddPlatformApiPlatformsPost: BodyAddPlatformApiPlatformsPost, apiResponseQueue: DispatchQueue = RommAPIAPI.apiResponseQueue, completion: @escaping ((_ data: PlatformSchema?, _ error: Error?) -> Void)) -> RequestTask {
        return addPlatformApiPlatformsPostWithRequestBuilder(bodyAddPlatformApiPlatformsPost: bodyAddPlatformApiPlatformsPost).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Add Platform
     - POST /api/platforms
     - Create a platform.
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - parameter bodyAddPlatformApiPlatformsPost: (body)  
     - returns: RequestBuilder<PlatformSchema> 
     */
    open class func addPlatformApiPlatformsPostWithRequestBuilder(bodyAddPlatformApiPlatformsPost: BodyAddPlatformApiPlatformsPost) -> RequestBuilder<PlatformSchema> {
        let localVariablePath = "/api/platforms"
        let localVariableURLString = RommAPIAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: bodyAddPlatformApiPlatformsPost)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<PlatformSchema>.Type = RommAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Delete Platform
     
     - parameter id: (path) Platform id. 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func deletePlatformApiPlatformsIdDelete(id: Int, apiResponseQueue: DispatchQueue = RommAPIAPI.apiResponseQueue, completion: @escaping ((_ data: MessageResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return deletePlatformApiPlatformsIdDeleteWithRequestBuilder(id: id).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Delete Platform
     - DELETE /api/platforms/{id}
     - Delete a platform.
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - parameter id: (path) Platform id. 
     - returns: RequestBuilder<MessageResponse> 
     */
    open class func deletePlatformApiPlatformsIdDeleteWithRequestBuilder(id: Int) -> RequestBuilder<MessageResponse> {
        var localVariablePath = "/api/platforms/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = RommAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<MessageResponse>.Type = RommAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get Platform
     
     - parameter id: (path) Platform id. 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getPlatformApiPlatformsIdGet(id: Int, apiResponseQueue: DispatchQueue = RommAPIAPI.apiResponseQueue, completion: @escaping ((_ data: PlatformSchema?, _ error: Error?) -> Void)) -> RequestTask {
        return getPlatformApiPlatformsIdGetWithRequestBuilder(id: id).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get Platform
     - GET /api/platforms/{id}
     - Retrieve a platform by ID.
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - parameter id: (path) Platform id. 
     - returns: RequestBuilder<PlatformSchema> 
     */
    open class func getPlatformApiPlatformsIdGetWithRequestBuilder(id: Int) -> RequestBuilder<PlatformSchema> {
        var localVariablePath = "/api/platforms/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = RommAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<PlatformSchema>.Type = RommAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get Platforms
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getPlatformsApiPlatformsGet(apiResponseQueue: DispatchQueue = RommAPIAPI.apiResponseQueue, completion: @escaping ((_ data: [PlatformSchema]?, _ error: Error?) -> Void)) -> RequestTask {
        return getPlatformsApiPlatformsGetWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get Platforms
     - GET /api/platforms
     - Retrieve platforms.
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - returns: RequestBuilder<[PlatformSchema]> 
     */
    open class func getPlatformsApiPlatformsGetWithRequestBuilder() -> RequestBuilder<[PlatformSchema]> {
        let localVariablePath = "/api/platforms"
        let localVariableURLString = RommAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[PlatformSchema]>.Type = RommAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get Supported Platforms
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getSupportedPlatformsApiPlatformsSupportedGet(apiResponseQueue: DispatchQueue = RommAPIAPI.apiResponseQueue, completion: @escaping ((_ data: [PlatformSchema]?, _ error: Error?) -> Void)) -> RequestTask {
        return getSupportedPlatformsApiPlatformsSupportedGetWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get Supported Platforms
     - GET /api/platforms/supported
     - Retrieve the list of supported platforms.
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - returns: RequestBuilder<[PlatformSchema]> 
     */
    open class func getSupportedPlatformsApiPlatformsSupportedGetWithRequestBuilder() -> RequestBuilder<[PlatformSchema]> {
        let localVariablePath = "/api/platforms/supported"
        let localVariableURLString = RommAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[PlatformSchema]>.Type = RommAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Update Platform
     
     - parameter id: (path) Platform id. 
     - parameter bodyUpdatePlatformApiPlatformsIdPut: (body)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func updatePlatformApiPlatformsIdPut(id: Int, bodyUpdatePlatformApiPlatformsIdPut: BodyUpdatePlatformApiPlatformsIdPut? = nil, apiResponseQueue: DispatchQueue = RommAPIAPI.apiResponseQueue, completion: @escaping ((_ data: PlatformSchema?, _ error: Error?) -> Void)) -> RequestTask {
        return updatePlatformApiPlatformsIdPutWithRequestBuilder(id: id, bodyUpdatePlatformApiPlatformsIdPut: bodyUpdatePlatformApiPlatformsIdPut).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Update Platform
     - PUT /api/platforms/{id}
     - Update a platform.
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - parameter id: (path) Platform id. 
     - parameter bodyUpdatePlatformApiPlatformsIdPut: (body)  (optional)
     - returns: RequestBuilder<PlatformSchema> 
     */
    open class func updatePlatformApiPlatformsIdPutWithRequestBuilder(id: Int, bodyUpdatePlatformApiPlatformsIdPut: BodyUpdatePlatformApiPlatformsIdPut? = nil) -> RequestBuilder<PlatformSchema> {
        var localVariablePath = "/api/platforms/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = RommAPIAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: bodyUpdatePlatformApiPlatformsIdPut)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<PlatformSchema>.Type = RommAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
