//
// RomsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class RomsAPI {

    /**
     Add Rom
     
     - parameter xUploadPlatform: (header) Platform internal id. 
     - parameter xUploadFilename: (header) The name of the file being uploaded. 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func addRomApiRomsPost(xUploadPlatform: Int, xUploadFilename: String, apiResponseQueue: DispatchQueue = RommAPIAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return addRomApiRomsPostWithRequestBuilder(xUploadPlatform: xUploadPlatform, xUploadFilename: xUploadFilename).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Add Rom
     - POST /api/roms
     - Upload a single rom.
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - parameter xUploadPlatform: (header) Platform internal id. 
     - parameter xUploadFilename: (header) The name of the file being uploaded. 
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func addRomApiRomsPostWithRequestBuilder(xUploadPlatform: Int, xUploadFilename: String) -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/api/roms"
        let localVariableURLString = RommAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "x-upload-platform": xUploadPlatform.encodeToJSON(),
            "x-upload-filename": xUploadFilename.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = RommAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Add Rom Manuals
     
     - parameter id: (path) Rom internal id. 
     - parameter xUploadFilename: (header) The name of the file being uploaded. 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func addRomManualsApiRomsIdManualsPost(id: Int, xUploadFilename: String, apiResponseQueue: DispatchQueue = RommAPIAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return addRomManualsApiRomsIdManualsPostWithRequestBuilder(id: id, xUploadFilename: xUploadFilename).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Add Rom Manuals
     - POST /api/roms/{id}/manuals
     - Upload manuals for a rom.
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - parameter id: (path) Rom internal id. 
     - parameter xUploadFilename: (header) The name of the file being uploaded. 
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func addRomManualsApiRomsIdManualsPostWithRequestBuilder(id: Int, xUploadFilename: String) -> RequestBuilder<AnyCodable> {
        var localVariablePath = "/api/roms/{id}/manuals"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = RommAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "x-upload-filename": xUploadFilename.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = RommAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Delete Roms
     
     - parameter bodyDeleteRomsApiRomsDeletePost: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func deleteRomsApiRomsDeletePost(bodyDeleteRomsApiRomsDeletePost: BodyDeleteRomsApiRomsDeletePost, apiResponseQueue: DispatchQueue = RommAPIAPI.apiResponseQueue, completion: @escaping ((_ data: MessageResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return deleteRomsApiRomsDeletePostWithRequestBuilder(bodyDeleteRomsApiRomsDeletePost: bodyDeleteRomsApiRomsDeletePost).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Delete Roms
     - POST /api/roms/delete
     - Delete roms.
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - parameter bodyDeleteRomsApiRomsDeletePost: (body)  
     - returns: RequestBuilder<MessageResponse> 
     */
    open class func deleteRomsApiRomsDeletePostWithRequestBuilder(bodyDeleteRomsApiRomsDeletePost: BodyDeleteRomsApiRomsDeletePost) -> RequestBuilder<MessageResponse> {
        let localVariablePath = "/api/roms/delete"
        let localVariableURLString = RommAPIAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: bodyDeleteRomsApiRomsDeletePost)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<MessageResponse>.Type = RommAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get Rom
     
     - parameter id: (path) Rom internal id. 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getRomApiRomsIdGet(id: Int, apiResponseQueue: DispatchQueue = RommAPIAPI.apiResponseQueue, completion: @escaping ((_ data: DetailedRomSchema?, _ error: Error?) -> Void)) -> RequestTask {
        return getRomApiRomsIdGetWithRequestBuilder(id: id).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get Rom
     - GET /api/roms/{id}
     - Retrieve a rom by ID.
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - parameter id: (path) Rom internal id. 
     - returns: RequestBuilder<DetailedRomSchema> 
     */
    open class func getRomApiRomsIdGetWithRequestBuilder(id: Int) -> RequestBuilder<DetailedRomSchema> {
        var localVariablePath = "/api/roms/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = RommAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<DetailedRomSchema>.Type = RommAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get Rom Content
     
     - parameter id: (path) Rom internal id. 
     - parameter fileName: (path) Zip file output name 
     - parameter fileIds: (query) Comma-separated list of file ids to download for multi-part roms. (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getRomContentApiRomsIdContentFileNameGet(id: Int, fileName: String, fileIds: String? = nil, apiResponseQueue: DispatchQueue = RommAPIAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return getRomContentApiRomsIdContentFileNameGetWithRequestBuilder(id: id, fileName: fileName, fileIds: fileIds).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get Rom Content
     - GET /api/roms/{id}/content/{file_name}
     - Download a rom.  This endpoint serves the content of the requested rom, as: - A single file for single file roms. - A zipped file for multi-part roms, including a .m3u file if applicable.
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - parameter id: (path) Rom internal id. 
     - parameter fileName: (path) Zip file output name 
     - parameter fileIds: (query) Comma-separated list of file ids to download for multi-part roms. (optional)
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func getRomContentApiRomsIdContentFileNameGetWithRequestBuilder(id: Int, fileName: String, fileIds: String? = nil) -> RequestBuilder<AnyCodable> {
        var localVariablePath = "/api/roms/{id}/content/{file_name}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let fileNamePreEscape = "\(APIHelper.mapValueToPathItem(fileName))"
        let fileNamePostEscape = fileNamePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{file_name}", with: fileNamePostEscape, options: .literal, range: nil)
        let localVariableURLString = RommAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "file_ids": (wrappedValue: fileIds?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = RommAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get Romfile
     
     - parameter id: (path) Rom file internal id. 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getRomfileApiRomsfilesIdGet(id: Int, apiResponseQueue: DispatchQueue = RommAPIAPI.apiResponseQueue, completion: @escaping ((_ data: RomFileSchema?, _ error: Error?) -> Void)) -> RequestTask {
        return getRomfileApiRomsfilesIdGetWithRequestBuilder(id: id).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get Romfile
     - GET /api/romsfiles/{id}
     - Retrieve a rom file by ID.
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - parameter id: (path) Rom file internal id. 
     - returns: RequestBuilder<RomFileSchema> 
     */
    open class func getRomfileApiRomsfilesIdGetWithRequestBuilder(id: Int) -> RequestBuilder<RomFileSchema> {
        var localVariablePath = "/api/romsfiles/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = RommAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<RomFileSchema>.Type = RommAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get Romfile Content
     
     - parameter id: (path) Rom file internal id. 
     - parameter fileName: (path) File name to download 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getRomfileContentApiRomsfilesIdContentFileNameGet(id: Int, fileName: String, apiResponseQueue: DispatchQueue = RommAPIAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return getRomfileContentApiRomsfilesIdContentFileNameGetWithRequestBuilder(id: id, fileName: fileName).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get Romfile Content
     - GET /api/romsfiles/{id}/content/{file_name}
     - Download a rom file.
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - parameter id: (path) Rom file internal id. 
     - parameter fileName: (path) File name to download 
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func getRomfileContentApiRomsfilesIdContentFileNameGetWithRequestBuilder(id: Int, fileName: String) -> RequestBuilder<AnyCodable> {
        var localVariablePath = "/api/romsfiles/{id}/content/{file_name}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let fileNamePreEscape = "\(APIHelper.mapValueToPathItem(fileName))"
        let fileNamePostEscape = fileNamePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{file_name}", with: fileNamePostEscape, options: .literal, range: nil)
        let localVariableURLString = RommAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = RommAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get Roms
     
     - parameter searchTerm: (query) Search term to filter roms. (optional)
     - parameter platformId: (query) Platform internal id. (optional)
     - parameter collectionId: (query) Collection internal id. (optional)
     - parameter virtualCollectionId: (query) Virtual collection internal id. (optional)
     - parameter matched: (query) Whether the rom matched a metadata source. (optional)
     - parameter favourite: (query) Whether the rom is marked as favourite. (optional)
     - parameter duplicate: (query) Whether the rom is marked as duplicate. (optional)
     - parameter playable: (query) Whether the rom is playable from the browser. (optional)
     - parameter missing: (query) Whether the rom is missing from the filesystem. (optional)
     - parameter hasRa: (query) Whether the rom has RetroAchievements data. (optional)
     - parameter verified: (query) Whether the rom is verified by Hasheous from the filesystem. (optional)
     - parameter groupByMetaId: (query) Whether to group roms by metadata ID (IGDB / Moby / ScreenScraper / RetroAchievements / LaunchBox). (optional, default to false)
     - parameter selectedGenre: (query) Associated genre. (optional)
     - parameter selectedFranchise: (query) Associated franchise. (optional)
     - parameter selectedCollection: (query) Associated collection. (optional)
     - parameter selectedCompany: (query) Associated company. (optional)
     - parameter selectedAgeRating: (query) Associated age rating. (optional)
     - parameter selectedStatus: (query) Game status, set by the current user. (optional)
     - parameter selectedRegion: (query) Associated region tag. (optional)
     - parameter selectedLanguage: (query) Associated language tag. (optional)
     - parameter orderBy: (query) Field to order results by. (optional, default to "name")
     - parameter orderDir: (query) Order direction, either &#39;asc&#39; or &#39;desc&#39;. (optional, default to "asc")
     - parameter limit: (query) Page size limit (optional, default to 50)
     - parameter offset: (query) Page offset (optional, default to 0)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getRomsApiRomsGet(searchTerm: String? = nil, platformId: Int? = nil, collectionId: Int? = nil, virtualCollectionId: String? = nil, matched: Bool? = nil, favourite: Bool? = nil, duplicate: Bool? = nil, playable: Bool? = nil, missing: Bool? = nil, hasRa: Bool? = nil, verified: Bool? = nil, groupByMetaId: Bool? = nil, selectedGenre: String? = nil, selectedFranchise: String? = nil, selectedCollection: String? = nil, selectedCompany: String? = nil, selectedAgeRating: String? = nil, selectedStatus: String? = nil, selectedRegion: String? = nil, selectedLanguage: String? = nil, orderBy: String? = nil, orderDir: String? = nil, limit: Int? = nil, offset: Int? = nil, apiResponseQueue: DispatchQueue = RommAPIAPI.apiResponseQueue, completion: @escaping ((_ data: CustomLimitOffsetPageSimpleRomSchema?, _ error: Error?) -> Void)) -> RequestTask {
        return getRomsApiRomsGetWithRequestBuilder(searchTerm: searchTerm, platformId: platformId, collectionId: collectionId, virtualCollectionId: virtualCollectionId, matched: matched, favourite: favourite, duplicate: duplicate, playable: playable, missing: missing, hasRa: hasRa, verified: verified, groupByMetaId: groupByMetaId, selectedGenre: selectedGenre, selectedFranchise: selectedFranchise, selectedCollection: selectedCollection, selectedCompany: selectedCompany, selectedAgeRating: selectedAgeRating, selectedStatus: selectedStatus, selectedRegion: selectedRegion, selectedLanguage: selectedLanguage, orderBy: orderBy, orderDir: orderDir, limit: limit, offset: offset).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get Roms
     - GET /api/roms
     - Retrieve roms.
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - parameter searchTerm: (query) Search term to filter roms. (optional)
     - parameter platformId: (query) Platform internal id. (optional)
     - parameter collectionId: (query) Collection internal id. (optional)
     - parameter virtualCollectionId: (query) Virtual collection internal id. (optional)
     - parameter matched: (query) Whether the rom matched a metadata source. (optional)
     - parameter favourite: (query) Whether the rom is marked as favourite. (optional)
     - parameter duplicate: (query) Whether the rom is marked as duplicate. (optional)
     - parameter playable: (query) Whether the rom is playable from the browser. (optional)
     - parameter missing: (query) Whether the rom is missing from the filesystem. (optional)
     - parameter hasRa: (query) Whether the rom has RetroAchievements data. (optional)
     - parameter verified: (query) Whether the rom is verified by Hasheous from the filesystem. (optional)
     - parameter groupByMetaId: (query) Whether to group roms by metadata ID (IGDB / Moby / ScreenScraper / RetroAchievements / LaunchBox). (optional, default to false)
     - parameter selectedGenre: (query) Associated genre. (optional)
     - parameter selectedFranchise: (query) Associated franchise. (optional)
     - parameter selectedCollection: (query) Associated collection. (optional)
     - parameter selectedCompany: (query) Associated company. (optional)
     - parameter selectedAgeRating: (query) Associated age rating. (optional)
     - parameter selectedStatus: (query) Game status, set by the current user. (optional)
     - parameter selectedRegion: (query) Associated region tag. (optional)
     - parameter selectedLanguage: (query) Associated language tag. (optional)
     - parameter orderBy: (query) Field to order results by. (optional, default to "name")
     - parameter orderDir: (query) Order direction, either &#39;asc&#39; or &#39;desc&#39;. (optional, default to "asc")
     - parameter limit: (query) Page size limit (optional, default to 50)
     - parameter offset: (query) Page offset (optional, default to 0)
     - returns: RequestBuilder<CustomLimitOffsetPageSimpleRomSchema> 
     */
    open class func getRomsApiRomsGetWithRequestBuilder(searchTerm: String? = nil, platformId: Int? = nil, collectionId: Int? = nil, virtualCollectionId: String? = nil, matched: Bool? = nil, favourite: Bool? = nil, duplicate: Bool? = nil, playable: Bool? = nil, missing: Bool? = nil, hasRa: Bool? = nil, verified: Bool? = nil, groupByMetaId: Bool? = nil, selectedGenre: String? = nil, selectedFranchise: String? = nil, selectedCollection: String? = nil, selectedCompany: String? = nil, selectedAgeRating: String? = nil, selectedStatus: String? = nil, selectedRegion: String? = nil, selectedLanguage: String? = nil, orderBy: String? = nil, orderDir: String? = nil, limit: Int? = nil, offset: Int? = nil) -> RequestBuilder<CustomLimitOffsetPageSimpleRomSchema> {
        let localVariablePath = "/api/roms"
        let localVariableURLString = RommAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "search_term": (wrappedValue: searchTerm?.encodeToJSON(), isExplode: true),
            "platform_id": (wrappedValue: platformId?.encodeToJSON(), isExplode: true),
            "collection_id": (wrappedValue: collectionId?.encodeToJSON(), isExplode: true),
            "virtual_collection_id": (wrappedValue: virtualCollectionId?.encodeToJSON(), isExplode: true),
            "matched": (wrappedValue: matched?.encodeToJSON(), isExplode: true),
            "favourite": (wrappedValue: favourite?.encodeToJSON(), isExplode: true),
            "duplicate": (wrappedValue: duplicate?.encodeToJSON(), isExplode: true),
            "playable": (wrappedValue: playable?.encodeToJSON(), isExplode: true),
            "missing": (wrappedValue: missing?.encodeToJSON(), isExplode: true),
            "has_ra": (wrappedValue: hasRa?.encodeToJSON(), isExplode: true),
            "verified": (wrappedValue: verified?.encodeToJSON(), isExplode: true),
            "group_by_meta_id": (wrappedValue: groupByMetaId?.encodeToJSON(), isExplode: true),
            "selected_genre": (wrappedValue: selectedGenre?.encodeToJSON(), isExplode: true),
            "selected_franchise": (wrappedValue: selectedFranchise?.encodeToJSON(), isExplode: true),
            "selected_collection": (wrappedValue: selectedCollection?.encodeToJSON(), isExplode: true),
            "selected_company": (wrappedValue: selectedCompany?.encodeToJSON(), isExplode: true),
            "selected_age_rating": (wrappedValue: selectedAgeRating?.encodeToJSON(), isExplode: true),
            "selected_status": (wrappedValue: selectedStatus?.encodeToJSON(), isExplode: true),
            "selected_region": (wrappedValue: selectedRegion?.encodeToJSON(), isExplode: true),
            "selected_language": (wrappedValue: selectedLanguage?.encodeToJSON(), isExplode: true),
            "order_by": (wrappedValue: orderBy?.encodeToJSON(), isExplode: true),
            "order_dir": (wrappedValue: orderDir?.encodeToJSON(), isExplode: true),
            "limit": (wrappedValue: limit?.encodeToJSON(), isExplode: true),
            "offset": (wrappedValue: offset?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CustomLimitOffsetPageSimpleRomSchema>.Type = RommAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Head Rom Content
     
     - parameter id: (path) Rom internal id. 
     - parameter fileName: (path) File name to download 
     - parameter fileIds: (query) Comma-separated list of file ids to download for multi-part roms. (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func headRomContentApiRomsIdContentFileNameHead(id: Int, fileName: String, fileIds: String? = nil, apiResponseQueue: DispatchQueue = RommAPIAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return headRomContentApiRomsIdContentFileNameHeadWithRequestBuilder(id: id, fileName: fileName, fileIds: fileIds).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Head Rom Content
     - HEAD /api/roms/{id}/content/{file_name}
     - Retrieve head information for a rom file download.
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - parameter id: (path) Rom internal id. 
     - parameter fileName: (path) File name to download 
     - parameter fileIds: (query) Comma-separated list of file ids to download for multi-part roms. (optional)
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func headRomContentApiRomsIdContentFileNameHeadWithRequestBuilder(id: Int, fileName: String, fileIds: String? = nil) -> RequestBuilder<AnyCodable> {
        var localVariablePath = "/api/roms/{id}/content/{file_name}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let fileNamePreEscape = "\(APIHelper.mapValueToPathItem(fileName))"
        let fileNamePostEscape = fileNamePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{file_name}", with: fileNamePostEscape, options: .literal, range: nil)
        let localVariableURLString = RommAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "file_ids": (wrappedValue: fileIds?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = RommAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "HEAD", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Update Rom
     
     - parameter id: (path) Rom internal id. 
     - parameter removeCover: (query) Whether to remove the cover image for this rom. (optional, default to false)
     - parameter unmatchMetadata: (query) Whether to remove the metadata matches for this game. (optional, default to false)
     - parameter artwork: (form)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func updateRomApiRomsIdPut(id: Int, removeCover: Bool? = nil, unmatchMetadata: Bool? = nil, artwork: URL? = nil, apiResponseQueue: DispatchQueue = RommAPIAPI.apiResponseQueue, completion: @escaping ((_ data: DetailedRomSchema?, _ error: Error?) -> Void)) -> RequestTask {
        return updateRomApiRomsIdPutWithRequestBuilder(id: id, removeCover: removeCover, unmatchMetadata: unmatchMetadata, artwork: artwork).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Update Rom
     - PUT /api/roms/{id}
     - Update a rom.
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - parameter id: (path) Rom internal id. 
     - parameter removeCover: (query) Whether to remove the cover image for this rom. (optional, default to false)
     - parameter unmatchMetadata: (query) Whether to remove the metadata matches for this game. (optional, default to false)
     - parameter artwork: (form)  (optional)
     - returns: RequestBuilder<DetailedRomSchema> 
     */
    open class func updateRomApiRomsIdPutWithRequestBuilder(id: Int, removeCover: Bool? = nil, unmatchMetadata: Bool? = nil, artwork: URL? = nil) -> RequestBuilder<DetailedRomSchema> {
        var localVariablePath = "/api/roms/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = RommAPIAPI.basePath + localVariablePath
        let localVariableFormParams: [String: Any?] = [
            "artwork": artwork?.encodeToJSON(),
        ]

        let localVariableNonNullParameters = APIHelper.rejectNil(localVariableFormParams)
        let localVariableParameters = APIHelper.convertBoolToString(localVariableNonNullParameters)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "remove_cover": (wrappedValue: removeCover?.encodeToJSON(), isExplode: true),
            "unmatch_metadata": (wrappedValue: unmatchMetadata?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "multipart/form-data",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<DetailedRomSchema>.Type = RommAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Update Rom User
     
     - parameter id: (path) Rom internal id. 
     - parameter bodyUpdateRomUserApiRomsIdPropsPut: (body)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func updateRomUserApiRomsIdPropsPut(id: Int, bodyUpdateRomUserApiRomsIdPropsPut: BodyUpdateRomUserApiRomsIdPropsPut? = nil, apiResponseQueue: DispatchQueue = RommAPIAPI.apiResponseQueue, completion: @escaping ((_ data: RomUserSchema?, _ error: Error?) -> Void)) -> RequestTask {
        return updateRomUserApiRomsIdPropsPutWithRequestBuilder(id: id, bodyUpdateRomUserApiRomsIdPropsPut: bodyUpdateRomUserApiRomsIdPropsPut).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Update Rom User
     - PUT /api/roms/{id}/props
     - Update rom data associated to the current user.
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - parameter id: (path) Rom internal id. 
     - parameter bodyUpdateRomUserApiRomsIdPropsPut: (body)  (optional)
     - returns: RequestBuilder<RomUserSchema> 
     */
    open class func updateRomUserApiRomsIdPropsPutWithRequestBuilder(id: Int, bodyUpdateRomUserApiRomsIdPropsPut: BodyUpdateRomUserApiRomsIdPropsPut? = nil) -> RequestBuilder<RomUserSchema> {
        var localVariablePath = "/api/roms/{id}/props"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = RommAPIAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: bodyUpdateRomUserApiRomsIdPropsPut)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<RomUserSchema>.Type = RommAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
