//
// SavesAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class SavesAPI {

    /**
     Add Save
     
     - parameter romId: (query)  
     - parameter emulator: (query)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func addSaveApiSavesPost(romId: Int, emulator: String? = nil, apiResponseQueue: DispatchQueue = RommAPIAPI.apiResponseQueue, completion: @escaping ((_ data: SaveSchema?, _ error: Error?) -> Void)) -> RequestTask {
        return addSaveApiSavesPostWithRequestBuilder(romId: romId, emulator: emulator).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Add Save
     - POST /api/saves
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - parameter romId: (query)  
     - parameter emulator: (query)  (optional)
     - returns: RequestBuilder<SaveSchema> 
     */
    open class func addSaveApiSavesPostWithRequestBuilder(romId: Int, emulator: String? = nil) -> RequestBuilder<SaveSchema> {
        let localVariablePath = "/api/saves"
        let localVariableURLString = RommAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "rom_id": (wrappedValue: romId.encodeToJSON(), isExplode: true),
            "emulator": (wrappedValue: emulator?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SaveSchema>.Type = RommAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Delete Saves
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func deleteSavesApiSavesDeletePost(apiResponseQueue: DispatchQueue = RommAPIAPI.apiResponseQueue, completion: @escaping ((_ data: [Int]?, _ error: Error?) -> Void)) -> RequestTask {
        return deleteSavesApiSavesDeletePostWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Delete Saves
     - POST /api/saves/delete
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - returns: RequestBuilder<[Int]> 
     */
    open class func deleteSavesApiSavesDeletePostWithRequestBuilder() -> RequestBuilder<[Int]> {
        let localVariablePath = "/api/saves/delete"
        let localVariableURLString = RommAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[Int]>.Type = RommAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get Save
     
     - parameter id: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getSaveApiSavesIdGet(id: Int, apiResponseQueue: DispatchQueue = RommAPIAPI.apiResponseQueue, completion: @escaping ((_ data: SaveSchema?, _ error: Error?) -> Void)) -> RequestTask {
        return getSaveApiSavesIdGetWithRequestBuilder(id: id).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get Save
     - GET /api/saves/{id}
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - parameter id: (path)  
     - returns: RequestBuilder<SaveSchema> 
     */
    open class func getSaveApiSavesIdGetWithRequestBuilder(id: Int) -> RequestBuilder<SaveSchema> {
        var localVariablePath = "/api/saves/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = RommAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SaveSchema>.Type = RommAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get Saves
     
     - parameter romId: (query)  (optional)
     - parameter platformId: (query)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getSavesApiSavesGet(romId: Int? = nil, platformId: Int? = nil, apiResponseQueue: DispatchQueue = RommAPIAPI.apiResponseQueue, completion: @escaping ((_ data: [SaveSchema]?, _ error: Error?) -> Void)) -> RequestTask {
        return getSavesApiSavesGetWithRequestBuilder(romId: romId, platformId: platformId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get Saves
     - GET /api/saves
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - parameter romId: (query)  (optional)
     - parameter platformId: (query)  (optional)
     - returns: RequestBuilder<[SaveSchema]> 
     */
    open class func getSavesApiSavesGetWithRequestBuilder(romId: Int? = nil, platformId: Int? = nil) -> RequestBuilder<[SaveSchema]> {
        let localVariablePath = "/api/saves"
        let localVariableURLString = RommAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "rom_id": (wrappedValue: romId?.encodeToJSON(), isExplode: true),
            "platform_id": (wrappedValue: platformId?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[SaveSchema]>.Type = RommAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Update Save
     
     - parameter id: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func updateSaveApiSavesIdPut(id: Int, apiResponseQueue: DispatchQueue = RommAPIAPI.apiResponseQueue, completion: @escaping ((_ data: SaveSchema?, _ error: Error?) -> Void)) -> RequestTask {
        return updateSaveApiSavesIdPutWithRequestBuilder(id: id).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Update Save
     - PUT /api/saves/{id}
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - parameter id: (path)  
     - returns: RequestBuilder<SaveSchema> 
     */
    open class func updateSaveApiSavesIdPutWithRequestBuilder(id: Int) -> RequestBuilder<SaveSchema> {
        var localVariablePath = "/api/saves/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = RommAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SaveSchema>.Type = RommAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
