//
// SearchAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class SearchAPI {

    /**
     Search Cover
     
     - parameter searchTerm: (query)  (optional, default to "")
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func searchCoverApiSearchCoverGet(searchTerm: String? = nil, apiResponseQueue: DispatchQueue = RommAPIAPI.apiResponseQueue, completion: @escaping ((_ data: [SearchCoverSchema]?, _ error: Error?) -> Void)) -> RequestTask {
        return searchCoverApiSearchCoverGetWithRequestBuilder(searchTerm: searchTerm).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Search Cover
     - GET /api/search/cover
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - parameter searchTerm: (query)  (optional, default to "")
     - returns: RequestBuilder<[SearchCoverSchema]> 
     */
    open class func searchCoverApiSearchCoverGetWithRequestBuilder(searchTerm: String? = nil) -> RequestBuilder<[SearchCoverSchema]> {
        let localVariablePath = "/api/search/cover"
        let localVariableURLString = RommAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "search_term": (wrappedValue: searchTerm?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[SearchCoverSchema]>.Type = RommAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Search Rom
     
     - parameter romId: (query)  
     - parameter searchTerm: (query)  (optional)
     - parameter searchBy: (query)  (optional, default to "name")
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func searchRomApiSearchRomsGet(romId: Int, searchTerm: String? = nil, searchBy: String? = nil, apiResponseQueue: DispatchQueue = RommAPIAPI.apiResponseQueue, completion: @escaping ((_ data: [SearchRomSchema]?, _ error: Error?) -> Void)) -> RequestTask {
        return searchRomApiSearchRomsGetWithRequestBuilder(romId: romId, searchTerm: searchTerm, searchBy: searchBy).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Search Rom
     - GET /api/search/roms
     - Search for rom in metadata providers  Args:     request (Request): FastAPI request     rom_id (int): Rom ID     source (str): Source of the rom     search_term (str, optional): Search term. Defaults to None.     search_by (str, optional): Search by name or ID. Defaults to \"name\".     search_extended (bool, optional): Search extended info. Defaults to False.  Returns:     list[SearchRomSchema]: List of matched roms
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - parameter romId: (query)  
     - parameter searchTerm: (query)  (optional)
     - parameter searchBy: (query)  (optional, default to "name")
     - returns: RequestBuilder<[SearchRomSchema]> 
     */
    open class func searchRomApiSearchRomsGetWithRequestBuilder(romId: Int, searchTerm: String? = nil, searchBy: String? = nil) -> RequestBuilder<[SearchRomSchema]> {
        let localVariablePath = "/api/search/roms"
        let localVariableURLString = RommAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "rom_id": (wrappedValue: romId.encodeToJSON(), isExplode: true),
            "search_term": (wrappedValue: searchTerm?.encodeToJSON(), isExplode: true),
            "search_by": (wrappedValue: searchBy?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[SearchRomSchema]>.Type = RommAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
