//
// StatesAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class StatesAPI {

    /**
     Add State
     
     - parameter romId: (query)  
     - parameter emulator: (query)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func addStateApiStatesPost(romId: Int, emulator: String? = nil, apiResponseQueue: DispatchQueue = RommAPIAPI.apiResponseQueue, completion: @escaping ((_ data: StateSchema?, _ error: Error?) -> Void)) -> RequestTask {
        return addStateApiStatesPostWithRequestBuilder(romId: romId, emulator: emulator).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Add State
     - POST /api/states
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - parameter romId: (query)  
     - parameter emulator: (query)  (optional)
     - returns: RequestBuilder<StateSchema> 
     */
    open class func addStateApiStatesPostWithRequestBuilder(romId: Int, emulator: String? = nil) -> RequestBuilder<StateSchema> {
        let localVariablePath = "/api/states"
        let localVariableURLString = RommAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "rom_id": (wrappedValue: romId.encodeToJSON(), isExplode: true),
            "emulator": (wrappedValue: emulator?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<StateSchema>.Type = RommAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Delete States
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func deleteStatesApiStatesDeletePost(apiResponseQueue: DispatchQueue = RommAPIAPI.apiResponseQueue, completion: @escaping ((_ data: [Int]?, _ error: Error?) -> Void)) -> RequestTask {
        return deleteStatesApiStatesDeletePostWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Delete States
     - POST /api/states/delete
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - returns: RequestBuilder<[Int]> 
     */
    open class func deleteStatesApiStatesDeletePostWithRequestBuilder() -> RequestBuilder<[Int]> {
        let localVariablePath = "/api/states/delete"
        let localVariableURLString = RommAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[Int]>.Type = RommAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get State
     
     - parameter id: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getStateApiStatesIdGet(id: Int, apiResponseQueue: DispatchQueue = RommAPIAPI.apiResponseQueue, completion: @escaping ((_ data: StateSchema?, _ error: Error?) -> Void)) -> RequestTask {
        return getStateApiStatesIdGetWithRequestBuilder(id: id).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get State
     - GET /api/states/{id}
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - parameter id: (path)  
     - returns: RequestBuilder<StateSchema> 
     */
    open class func getStateApiStatesIdGetWithRequestBuilder(id: Int) -> RequestBuilder<StateSchema> {
        var localVariablePath = "/api/states/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = RommAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<StateSchema>.Type = RommAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get States
     
     - parameter romId: (query)  (optional)
     - parameter platformId: (query)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getStatesApiStatesGet(romId: Int? = nil, platformId: Int? = nil, apiResponseQueue: DispatchQueue = RommAPIAPI.apiResponseQueue, completion: @escaping ((_ data: [StateSchema]?, _ error: Error?) -> Void)) -> RequestTask {
        return getStatesApiStatesGetWithRequestBuilder(romId: romId, platformId: platformId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get States
     - GET /api/states
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - parameter romId: (query)  (optional)
     - parameter platformId: (query)  (optional)
     - returns: RequestBuilder<[StateSchema]> 
     */
    open class func getStatesApiStatesGetWithRequestBuilder(romId: Int? = nil, platformId: Int? = nil) -> RequestBuilder<[StateSchema]> {
        let localVariablePath = "/api/states"
        let localVariableURLString = RommAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "rom_id": (wrappedValue: romId?.encodeToJSON(), isExplode: true),
            "platform_id": (wrappedValue: platformId?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[StateSchema]>.Type = RommAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Update State
     
     - parameter id: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func updateStateApiStatesIdPut(id: Int, apiResponseQueue: DispatchQueue = RommAPIAPI.apiResponseQueue, completion: @escaping ((_ data: StateSchema?, _ error: Error?) -> Void)) -> RequestTask {
        return updateStateApiStatesIdPutWithRequestBuilder(id: id).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Update State
     - PUT /api/states/{id}
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - parameter id: (path)  
     - returns: RequestBuilder<StateSchema> 
     */
    open class func updateStateApiStatesIdPutWithRequestBuilder(id: Int) -> RequestBuilder<StateSchema> {
        var localVariablePath = "/api/states/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = RommAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<StateSchema>.Type = RommAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
