# Snapfile for romm App Store Screenshots

# A list of devices you want to take the screenshots from
devices([
  "iPhone 16 Pro"
])

languages([
  "en-US"
])

# Project/Workspace path
workspace("romm/romm.xcodeproj/project.xcworkspace")

# The name of the scheme which contains the UI Tests
scheme("romm")

# Where should the resulting screenshots be stored?
output_directory("./fastlane/screenshots")

# Clear previous screenshots
clear_previous_screenshots(true)

# Disable animations for cleaner screenshots
override_status_bar(true)

# Erase simulator before running
erase_simulator(true)

# Reinstall app before running
reinstall_app(true)

# Arguments to pass to the app on launch
launch_arguments([
  "-FASTLANE_SNAPSHOT YES"
])

# For more information about all available options run
# fastlane action snapshot
