# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
  "iPhone 16 Pro Max",
  "iPhone 16 Pro",
  "iPhone SE (3rd generation)",
  "iPad Pro (13-inch) (M4)"
])

languages([
  "en-US"
])

# The name of the scheme which contains the UI Tests
scheme("rommUITests")

# Where should the resulting screenshots be stored?
output_directory("./fastlane/screenshots")

# Clear previous screenshots
clear_previous_screenshots(true)

# Arguments to pass to the app on launch
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane action snapshot
