//
// AuthAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class AuthAPI {

    /**
     Auth Openid
     
     - returns: Any
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func authOpenidApiOauthOpenidGet() async throws -> String {
        return try await authOpenidApiOauthOpenidGetWithRequestBuilder().execute().body
    }

    /**
     Auth Openid
     - GET /api/oauth/openid
     - OIDC callback endpoint  Args:     request (Request): Fastapi Request object  Raises:     OIDCDisabledException: OAuth is disabled     OIDCNotConfiguredException: OAuth not configured     AuthCredentialsException: Invalid credentials     UserDisabledException: Auth is disabled  Returns:     RedirectResponse: Redirect to home page
     - returns: RequestBuilder<String> 
     */
    open class func authOpenidApiOauthOpenidGetWithRequestBuilder() -> RequestBuilder<String> {
        let localVariablePath = "/api/oauth/openid"
        let localVariableURLString = rommAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<String>.Type = rommAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Login
     
     - returns: Any
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func loginApiLoginPost() async throws -> String {
        return try await loginApiLoginPostWithRequestBuilder().execute().body
    }

    /**
     Login
     - POST /api/login
     - Session login endpoint  Args:     request (Request): Fastapi Request object     credentials: Defaults to Depends(HTTPBasic()).  Raises:     CredentialsException: Invalid credentials     UserDisabledException: Auth is disabled
     - BASIC:
       - type: http
       - name: HTTPBasic
     - returns: RequestBuilder<String> 
     */
    open class func loginApiLoginPostWithRequestBuilder() -> RequestBuilder<String> {
        let localVariablePath = "/api/login"
        let localVariableURLString = rommAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<String>.Type = rommAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Login Via Openid
     
     - returns: Any
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func loginViaOpenidApiLoginOpenidGet() async throws -> String {
        return try await loginViaOpenidApiLoginOpenidGetWithRequestBuilder().execute().body
    }

    /**
     Login Via Openid
     - GET /api/login/openid
     - OIDC login endpoint  Args:     request (Request): Fastapi Request object  Raises:     OIDCDisabledException: OAuth is disabled     OIDCNotConfiguredException: OAuth not configured  Returns:     RedirectResponse: Redirect to OIDC provider
     - returns: RequestBuilder<String> 
     */
    open class func loginViaOpenidApiLoginOpenidGetWithRequestBuilder() -> RequestBuilder<String> {
        let localVariablePath = "/api/login/openid"
        let localVariableURLString = rommAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<String>.Type = rommAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Logout
     
     - returns: Any
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func logoutApiLogoutPost() async throws -> String {
        return try await logoutApiLogoutPostWithRequestBuilder().execute().body
    }

    /**
     Logout
     - POST /api/logout
     - Session logout endpoint  Args:     request (Request): Fastapi Request object
     - returns: RequestBuilder<String> 
     */
    open class func logoutApiLogoutPostWithRequestBuilder() -> RequestBuilder<String> {
        let localVariablePath = "/api/logout"
        let localVariableURLString = rommAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<String>.Type = rommAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Request Password Reset
     
     - parameter bodyRequestPasswordResetApiForgotPasswordPost: (body)  
     - returns: Any
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func requestPasswordResetApiForgotPasswordPost(bodyRequestPasswordResetApiForgotPasswordPost: BodyRequestPasswordResetApiForgotPasswordPost) async throws -> String {
        return try await requestPasswordResetApiForgotPasswordPostWithRequestBuilder(bodyRequestPasswordResetApiForgotPasswordPost: bodyRequestPasswordResetApiForgotPasswordPost).execute().body
    }

    /**
     Request Password Reset
     - POST /api/forgot-password
     - Request a password reset link for the user.  Args:     username (str): Username of the user requesting the reset Returns:     None: Returns 200 OK status
     - parameter bodyRequestPasswordResetApiForgotPasswordPost: (body)  
     - returns: RequestBuilder<String> 
     */
    open class func requestPasswordResetApiForgotPasswordPostWithRequestBuilder(bodyRequestPasswordResetApiForgotPasswordPost: BodyRequestPasswordResetApiForgotPasswordPost) -> RequestBuilder<String> {
        let localVariablePath = "/api/forgot-password"
        let localVariableURLString = rommAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: bodyRequestPasswordResetApiForgotPasswordPost)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<String>.Type = rommAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Reset Password
     
     - parameter bodyResetPasswordApiResetPasswordPost: (body)  
     - returns: Any
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func resetPasswordApiResetPasswordPost(bodyResetPasswordApiResetPasswordPost: BodyResetPasswordApiResetPasswordPost) async throws -> String {
        return try await resetPasswordApiResetPasswordPostWithRequestBuilder(bodyResetPasswordApiResetPasswordPost: bodyResetPasswordApiResetPasswordPost).execute().body
    }

    /**
     Reset Password
     - POST /api/reset-password
     - Reset password using the token.  Args:     token (str): Reset token from the URL     new_password (str): New user password  Returns:     None: Returns 200 OK status
     - parameter bodyResetPasswordApiResetPasswordPost: (body)  
     - returns: RequestBuilder<String> 
     */
    open class func resetPasswordApiResetPasswordPostWithRequestBuilder(bodyResetPasswordApiResetPasswordPost: BodyResetPasswordApiResetPasswordPost) -> RequestBuilder<String> {
        let localVariablePath = "/api/reset-password"
        let localVariableURLString = rommAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: bodyResetPasswordApiResetPasswordPost)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<String>.Type = rommAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Token
     
     - parameter grantType: (form)  (optional, default to "password")
     - parameter scope: (form)  (optional, default to "")
     - parameter username: (form)  (optional)
     - parameter password: (form)  (optional)
     - parameter clientId: (form)  (optional)
     - parameter clientSecret: (form)  (optional)
     - parameter refreshToken: (form)  (optional)
     - returns: TokenResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func tokenApiTokenPost(grantType: String? = nil, scope: String? = nil, username: String? = nil, password: String? = nil, clientId: String? = nil, clientSecret: String? = nil, refreshToken: String? = nil) async throws -> TokenResponse {
        return try await tokenApiTokenPostWithRequestBuilder(grantType: grantType, scope: scope, username: username, password: password, clientId: clientId, clientSecret: clientSecret, refreshToken: refreshToken).execute().body
    }

    /**
     Token
     - POST /api/token
     - OAuth2 token endpoint  Args:     form_data (Annotated[OAuth2RequestForm, Depends): Form Data with OAuth2 info  Raises:     HTTPException: Missing refresh token     HTTPException: Invalid refresh token     HTTPException: Missing username or password     HTTPException: Invalid username or password     HTTPException: Client credentials are not yet supported     HTTPException: Invalid or unsupported grant type     HTTPException: Insufficient scope  Returns:     TokenResponse: TypedDict with the new generated token info
     - parameter grantType: (form)  (optional, default to "password")
     - parameter scope: (form)  (optional, default to "")
     - parameter username: (form)  (optional)
     - parameter password: (form)  (optional)
     - parameter clientId: (form)  (optional)
     - parameter clientSecret: (form)  (optional)
     - parameter refreshToken: (form)  (optional)
     - returns: RequestBuilder<TokenResponse> 
     */
    open class func tokenApiTokenPostWithRequestBuilder(grantType: String? = nil, scope: String? = nil, username: String? = nil, password: String? = nil, clientId: String? = nil, clientSecret: String? = nil, refreshToken: String? = nil) -> RequestBuilder<TokenResponse> {
        let localVariablePath = "/api/token"
        let localVariableURLString = rommAPI.basePath + localVariablePath
        let localVariableFormParams: [String: Any?] = [
            "grant_type": grantType?.encodeToJSON(),
            "scope": scope?.encodeToJSON(),
            "username": username?.encodeToJSON(),
            "password": password?.encodeToJSON(),
            "client_id": clientId?.encodeToJSON(),
            "client_secret": clientSecret?.encodeToJSON(),
            "refresh_token": refreshToken?.encodeToJSON(),
        ]

        let localVariableNonNullParameters = APIHelper.rejectNil(localVariableFormParams)
        let localVariableParameters = APIHelper.convertBoolToString(localVariableNonNullParameters)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/x-www-form-urlencoded",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<TokenResponse>.Type = rommAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
