//
// CollectionsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class CollectionsAPI {

    /**
     Add Collection
     
     - parameter artwork: (form)  (optional)
     - returns: CollectionSchema
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func addCollectionApiCollectionsPost(artwork: URL? = nil) async throws -> CollectionSchema {
        return try await addCollectionApiCollectionsPostWithRequestBuilder(artwork: artwork).execute().body
    }

    /**
     Add Collection
     - POST /api/collections
     - Create collection endpoint  Args:     request (Request): Fastapi Request object  Returns:     CollectionSchema: Just created collection
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - parameter artwork: (form)  (optional)
     - returns: RequestBuilder<CollectionSchema> 
     */
    open class func addCollectionApiCollectionsPostWithRequestBuilder(artwork: URL? = nil) -> RequestBuilder<CollectionSchema> {
        let localVariablePath = "/api/collections"
        let localVariableURLString = rommAPI.basePath + localVariablePath
        let localVariableFormParams: [String: Any?] = [
            "artwork": artwork?.encodeToJSON(),
        ]

        let localVariableNonNullParameters = APIHelper.rejectNil(localVariableFormParams)
        let localVariableParameters = APIHelper.convertBoolToString(localVariableNonNullParameters)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "multipart/form-data",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CollectionSchema>.Type = rommAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Add Smart Collection
     
     - returns: SmartCollectionSchema
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func addSmartCollectionApiCollectionsSmartPost() async throws -> SmartCollectionSchema {
        return try await addSmartCollectionApiCollectionsSmartPostWithRequestBuilder().execute().body
    }

    /**
     Add Smart Collection
     - POST /api/collections/smart
     - Create smart collection endpoint  Args:     request (Request): Fastapi Request object  Returns:     SmartCollectionSchema: Just created smart collection
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - returns: RequestBuilder<SmartCollectionSchema> 
     */
    open class func addSmartCollectionApiCollectionsSmartPostWithRequestBuilder() -> RequestBuilder<SmartCollectionSchema> {
        let localVariablePath = "/api/collections/smart"
        let localVariableURLString = rommAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SmartCollectionSchema>.Type = rommAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Delete Collection
     
     - parameter id: (path)  
     - returns: Any
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func deleteCollectionApiCollectionsIdDelete(id: Int) async throws -> String {
        return try await deleteCollectionApiCollectionsIdDeleteWithRequestBuilder(id: id).execute().body
    }

    /**
     Delete Collection
     - DELETE /api/collections/{id}
     - Delete collections endpoint  Args:     request (Request): Fastapi Request object     {         \"collections\": List of rom's ids to delete     }  Raises:     HTTPException: Collection not found
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - parameter id: (path)  
     - returns: RequestBuilder<String> 
     */
    open class func deleteCollectionApiCollectionsIdDeleteWithRequestBuilder(id: Int) -> RequestBuilder<String> {
        var localVariablePath = "/api/collections/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = rommAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<String>.Type = rommAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Delete Smart Collection
     
     - parameter id: (path)  
     - returns: Any
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func deleteSmartCollectionApiCollectionsSmartIdDelete(id: Int) async throws -> String {
        return try await deleteSmartCollectionApiCollectionsSmartIdDeleteWithRequestBuilder(id: id).execute().body
    }

    /**
     Delete Smart Collection
     - DELETE /api/collections/smart/{id}
     - Delete smart collection endpoint  Args:     request (Request): Fastapi Request object     id (int): Smart collection id
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - parameter id: (path)  
     - returns: RequestBuilder<String> 
     */
    open class func deleteSmartCollectionApiCollectionsSmartIdDeleteWithRequestBuilder(id: Int) -> RequestBuilder<String> {
        var localVariablePath = "/api/collections/smart/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = rommAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<String>.Type = rommAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get Collection
     
     - parameter id: (path)  
     - returns: CollectionSchema
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getCollectionApiCollectionsIdGet(id: Int) async throws -> CollectionSchema {
        return try await getCollectionApiCollectionsIdGetWithRequestBuilder(id: id).execute().body
    }

    /**
     Get Collection
     - GET /api/collections/{id}
     - Get collections endpoint  Args:     request (Request): Fastapi Request object     id (int, optional): Collection id. Defaults to None.  Returns:     CollectionSchema: Collection
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - parameter id: (path)  
     - returns: RequestBuilder<CollectionSchema> 
     */
    open class func getCollectionApiCollectionsIdGetWithRequestBuilder(id: Int) -> RequestBuilder<CollectionSchema> {
        var localVariablePath = "/api/collections/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = rommAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CollectionSchema>.Type = rommAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get Collections
     
     - returns: [CollectionSchema]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getCollectionsApiCollectionsGet() async throws -> [CollectionSchema] {
        return try await getCollectionsApiCollectionsGetWithRequestBuilder().execute().body
    }

    /**
     Get Collections
     - GET /api/collections
     - Get collections endpoint  Args:     request (Request): Fastapi Request object     id (int, optional): Collection id. Defaults to None.  Returns:     list[CollectionSchema]: List of collections
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - returns: RequestBuilder<[CollectionSchema]> 
     */
    open class func getCollectionsApiCollectionsGetWithRequestBuilder() -> RequestBuilder<[CollectionSchema]> {
        let localVariablePath = "/api/collections"
        let localVariableURLString = rommAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[CollectionSchema]>.Type = rommAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get Smart Collection
     
     - parameter id: (path)  
     - returns: SmartCollectionSchema
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getSmartCollectionApiCollectionsSmartIdGet(id: Int) async throws -> SmartCollectionSchema {
        return try await getSmartCollectionApiCollectionsSmartIdGetWithRequestBuilder(id: id).execute().body
    }

    /**
     Get Smart Collection
     - GET /api/collections/smart/{id}
     - Get smart collection endpoint  Args:     request (Request): Fastapi Request object     id (int): Smart collection id  Returns:     SmartCollectionSchema: Smart collection
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - parameter id: (path)  
     - returns: RequestBuilder<SmartCollectionSchema> 
     */
    open class func getSmartCollectionApiCollectionsSmartIdGetWithRequestBuilder(id: Int) -> RequestBuilder<SmartCollectionSchema> {
        var localVariablePath = "/api/collections/smart/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = rommAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SmartCollectionSchema>.Type = rommAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get Smart Collections
     
     - returns: [SmartCollectionSchema]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getSmartCollectionsApiCollectionsSmartGet() async throws -> [SmartCollectionSchema] {
        return try await getSmartCollectionsApiCollectionsSmartGetWithRequestBuilder().execute().body
    }

    /**
     Get Smart Collections
     - GET /api/collections/smart
     - Get smart collections endpoint  Args:     request (Request): Fastapi Request object  Returns:     list[SmartCollectionSchema]: List of smart collections
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - returns: RequestBuilder<[SmartCollectionSchema]> 
     */
    open class func getSmartCollectionsApiCollectionsSmartGetWithRequestBuilder() -> RequestBuilder<[SmartCollectionSchema]> {
        let localVariablePath = "/api/collections/smart"
        let localVariableURLString = rommAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[SmartCollectionSchema]>.Type = rommAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get Virtual Collection
     
     - parameter id: (path)  
     - returns: VirtualCollectionSchema
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getVirtualCollectionApiCollectionsVirtualIdGet(id: String) async throws -> VirtualCollectionSchema {
        return try await getVirtualCollectionApiCollectionsVirtualIdGetWithRequestBuilder(id: id).execute().body
    }

    /**
     Get Virtual Collection
     - GET /api/collections/virtual/{id}
     - Get virtual collections endpoint  Args:     request (Request): Fastapi Request object     id (str): Virtual collection id  Returns:     VirtualCollectionSchema: Virtual collection
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - parameter id: (path)  
     - returns: RequestBuilder<VirtualCollectionSchema> 
     */
    open class func getVirtualCollectionApiCollectionsVirtualIdGetWithRequestBuilder(id: String) -> RequestBuilder<VirtualCollectionSchema> {
        var localVariablePath = "/api/collections/virtual/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = rommAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<VirtualCollectionSchema>.Type = rommAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get Virtual Collections
     
     - parameter type: (query)  
     - parameter limit: (query)  (optional)
     - returns: [VirtualCollectionSchema]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getVirtualCollectionsApiCollectionsVirtualGet(type: String, limit: Int? = nil) async throws -> [VirtualCollectionSchema] {
        return try await getVirtualCollectionsApiCollectionsVirtualGetWithRequestBuilder(type: type, limit: limit).execute().body
    }

    /**
     Get Virtual Collections
     - GET /api/collections/virtual
     - Get virtual collections endpoint  Args:     request (Request): Fastapi Request object  Returns:     list[VirtualCollectionSchema]: List of virtual collections
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - parameter type: (query)  
     - parameter limit: (query)  (optional)
     - returns: RequestBuilder<[VirtualCollectionSchema]> 
     */
    open class func getVirtualCollectionsApiCollectionsVirtualGetWithRequestBuilder(type: String, limit: Int? = nil) -> RequestBuilder<[VirtualCollectionSchema]> {
        let localVariablePath = "/api/collections/virtual"
        let localVariableURLString = rommAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "type": (wrappedValue: type.encodeToJSON(), isExplode: true),
            "limit": (wrappedValue: limit?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[VirtualCollectionSchema]>.Type = rommAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Update Collection
     
     - parameter id: (path)  
     - parameter removeCover: (query)  (optional, default to false)
     - parameter isPublic: (query)  (optional)
     - parameter artwork: (form)  (optional)
     - returns: CollectionSchema
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func updateCollectionApiCollectionsIdPut(id: Int, removeCover: Bool? = nil, isPublic: Bool? = nil, artwork: URL? = nil) async throws -> CollectionSchema {
        return try await updateCollectionApiCollectionsIdPutWithRequestBuilder(id: id, removeCover: removeCover, isPublic: isPublic, artwork: artwork).execute().body
    }

    /**
     Update Collection
     - PUT /api/collections/{id}
     - Update collection endpoint  Args:     request (Request): Fastapi Request object  Returns:     CollectionSchema: Updated collection
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - parameter id: (path)  
     - parameter removeCover: (query)  (optional, default to false)
     - parameter isPublic: (query)  (optional)
     - parameter artwork: (form)  (optional)
     - returns: RequestBuilder<CollectionSchema> 
     */
    open class func updateCollectionApiCollectionsIdPutWithRequestBuilder(id: Int, removeCover: Bool? = nil, isPublic: Bool? = nil, artwork: URL? = nil) -> RequestBuilder<CollectionSchema> {
        var localVariablePath = "/api/collections/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = rommAPI.basePath + localVariablePath
        let localVariableFormParams: [String: Any?] = [
            "artwork": artwork?.encodeToJSON(),
        ]

        let localVariableNonNullParameters = APIHelper.rejectNil(localVariableFormParams)
        let localVariableParameters = APIHelper.convertBoolToString(localVariableNonNullParameters)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "remove_cover": (wrappedValue: removeCover?.encodeToJSON(), isExplode: true),
            "is_public": (wrappedValue: isPublic?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "multipart/form-data",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CollectionSchema>.Type = rommAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Update Smart Collection
     
     - parameter id: (path)  
     - parameter isPublic: (query)  (optional)
     - returns: SmartCollectionSchema
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func updateSmartCollectionApiCollectionsSmartIdPut(id: Int, isPublic: Bool? = nil) async throws -> SmartCollectionSchema {
        return try await updateSmartCollectionApiCollectionsSmartIdPutWithRequestBuilder(id: id, isPublic: isPublic).execute().body
    }

    /**
     Update Smart Collection
     - PUT /api/collections/smart/{id}
     - Update smart collection endpoint  Args:     request (Request): Fastapi Request object     id (int): Smart collection id  Returns:     SmartCollectionSchema: Updated smart collection
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - parameter id: (path)  
     - parameter isPublic: (query)  (optional)
     - returns: RequestBuilder<SmartCollectionSchema> 
     */
    open class func updateSmartCollectionApiCollectionsSmartIdPutWithRequestBuilder(id: Int, isPublic: Bool? = nil) -> RequestBuilder<SmartCollectionSchema> {
        var localVariablePath = "/api/collections/smart/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = rommAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "is_public": (wrappedValue: isPublic?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SmartCollectionSchema>.Type = rommAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
