//
// ConfigAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class ConfigAPI {

    /**
     Add Exclusion
     
     - returns: Any
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func addExclusionApiConfigExcludePost() async throws -> String {
        return try await addExclusionApiConfigExcludePostWithRequestBuilder().execute().body
    }

    /**
     Add Exclusion
     - POST /api/config/exclude
     - Add platform exclusion to the configuration
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - returns: RequestBuilder<String> 
     */
    open class func addExclusionApiConfigExcludePostWithRequestBuilder() -> RequestBuilder<String> {
        let localVariablePath = "/api/config/exclude"
        let localVariableURLString = rommAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<String>.Type = rommAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Add Platform Binding
     
     - returns: Any
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func addPlatformBindingApiConfigSystemPlatformsPost() async throws -> String {
        return try await addPlatformBindingApiConfigSystemPlatformsPostWithRequestBuilder().execute().body
    }

    /**
     Add Platform Binding
     - POST /api/config/system/platforms
     - Add platform binding to the configuration
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - returns: RequestBuilder<String> 
     */
    open class func addPlatformBindingApiConfigSystemPlatformsPostWithRequestBuilder() -> RequestBuilder<String> {
        let localVariablePath = "/api/config/system/platforms"
        let localVariableURLString = rommAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<String>.Type = rommAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Add Platform Version
     
     - returns: Any
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func addPlatformVersionApiConfigSystemVersionsPost() async throws -> String {
        return try await addPlatformVersionApiConfigSystemVersionsPostWithRequestBuilder().execute().body
    }

    /**
     Add Platform Version
     - POST /api/config/system/versions
     - Add platform version to the configuration
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - returns: RequestBuilder<String> 
     */
    open class func addPlatformVersionApiConfigSystemVersionsPostWithRequestBuilder() -> RequestBuilder<String> {
        let localVariablePath = "/api/config/system/versions"
        let localVariableURLString = rommAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<String>.Type = rommAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Delete Exclusion
     
     - parameter exclusionType: (path)  
     - parameter exclusionValue: (path)  
     - returns: Any
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func deleteExclusionApiConfigExcludeExclusionTypeExclusionValueDelete(exclusionType: String, exclusionValue: String) async throws -> String {
        return try await deleteExclusionApiConfigExcludeExclusionTypeExclusionValueDeleteWithRequestBuilder(exclusionType: exclusionType, exclusionValue: exclusionValue).execute().body
    }

    /**
     Delete Exclusion
     - DELETE /api/config/exclude/{exclusion_type}/{exclusion_value}
     - Delete platform binding from the configuration
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - parameter exclusionType: (path)  
     - parameter exclusionValue: (path)  
     - returns: RequestBuilder<String> 
     */
    open class func deleteExclusionApiConfigExcludeExclusionTypeExclusionValueDeleteWithRequestBuilder(exclusionType: String, exclusionValue: String) -> RequestBuilder<String> {
        var localVariablePath = "/api/config/exclude/{exclusion_type}/{exclusion_value}"
        let exclusionTypePreEscape = "\(APIHelper.mapValueToPathItem(exclusionType))"
        let exclusionTypePostEscape = exclusionTypePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{exclusion_type}", with: exclusionTypePostEscape, options: .literal, range: nil)
        let exclusionValuePreEscape = "\(APIHelper.mapValueToPathItem(exclusionValue))"
        let exclusionValuePostEscape = exclusionValuePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{exclusion_value}", with: exclusionValuePostEscape, options: .literal, range: nil)
        let localVariableURLString = rommAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<String>.Type = rommAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Delete Platform Binding
     
     - parameter fsSlug: (path)  
     - returns: Any
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func deletePlatformBindingApiConfigSystemPlatformsFsSlugDelete(fsSlug: String) async throws -> String {
        return try await deletePlatformBindingApiConfigSystemPlatformsFsSlugDeleteWithRequestBuilder(fsSlug: fsSlug).execute().body
    }

    /**
     Delete Platform Binding
     - DELETE /api/config/system/platforms/{fs_slug}
     - Delete platform binding from the configuration
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - parameter fsSlug: (path)  
     - returns: RequestBuilder<String> 
     */
    open class func deletePlatformBindingApiConfigSystemPlatformsFsSlugDeleteWithRequestBuilder(fsSlug: String) -> RequestBuilder<String> {
        var localVariablePath = "/api/config/system/platforms/{fs_slug}"
        let fsSlugPreEscape = "\(APIHelper.mapValueToPathItem(fsSlug))"
        let fsSlugPostEscape = fsSlugPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{fs_slug}", with: fsSlugPostEscape, options: .literal, range: nil)
        let localVariableURLString = rommAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<String>.Type = rommAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Delete Platform Version
     
     - parameter fsSlug: (path)  
     - returns: Any
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func deletePlatformVersionApiConfigSystemVersionsFsSlugDelete(fsSlug: String) async throws -> String {
        return try await deletePlatformVersionApiConfigSystemVersionsFsSlugDeleteWithRequestBuilder(fsSlug: fsSlug).execute().body
    }

    /**
     Delete Platform Version
     - DELETE /api/config/system/versions/{fs_slug}
     - Delete platform version from the configuration
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - parameter fsSlug: (path)  
     - returns: RequestBuilder<String> 
     */
    open class func deletePlatformVersionApiConfigSystemVersionsFsSlugDeleteWithRequestBuilder(fsSlug: String) -> RequestBuilder<String> {
        var localVariablePath = "/api/config/system/versions/{fs_slug}"
        let fsSlugPreEscape = "\(APIHelper.mapValueToPathItem(fsSlug))"
        let fsSlugPostEscape = fsSlugPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{fs_slug}", with: fsSlugPostEscape, options: .literal, range: nil)
        let localVariableURLString = rommAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<String>.Type = rommAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get Config
     
     - returns: ConfigResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getConfigApiConfigGet() async throws -> ConfigResponse {
        return try await getConfigApiConfigGetWithRequestBuilder().execute().body
    }

    /**
     Get Config
     - GET /api/config
     - Get config endpoint  Returns:     ConfigResponse: RomM's configuration
     - returns: RequestBuilder<ConfigResponse> 
     */
    open class func getConfigApiConfigGetWithRequestBuilder() -> RequestBuilder<ConfigResponse> {
        let localVariablePath = "/api/config"
        let localVariableURLString = rommAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ConfigResponse>.Type = rommAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
