//
// FeedsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class FeedsAPI {

    /**
     Platforms Webrcade Feed
     
     - returns: WebrcadeFeedSchema
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func platformsWebrcadeFeedApiWebrcadeFeedGet() async throws -> WebrcadeFeedSchema {
        return try await platformsWebrcadeFeedApiWebrcadeFeedGetWithRequestBuilder().execute().body
    }

    /**
     Platforms Webrcade Feed
     - GET /api/webrcade/feed
     - Get webrcade feed endpoint https://docs.webrcade.com/feeds/format/  Args:     request (Request): Fastapi Request object  Returns:     WebrcadeFeedSchema: Webrcade feed object schema
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - returns: RequestBuilder<WebrcadeFeedSchema> 
     */
    open class func platformsWebrcadeFeedApiWebrcadeFeedGetWithRequestBuilder() -> RequestBuilder<WebrcadeFeedSchema> {
        let localVariablePath = "/api/webrcade/feed"
        let localVariableURLString = rommAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<WebrcadeFeedSchema>.Type = rommAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Tinfoil Index Feed
     
     - parameter slug: (query)  (optional, default to "switch")
     - returns: TinfoilFeedSchema
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func tinfoilIndexFeedApiTinfoilFeedGet(slug: String? = nil) async throws -> TinfoilFeedSchema {
        return try await tinfoilIndexFeedApiTinfoilFeedGetWithRequestBuilder(slug: slug).execute().body
    }

    /**
     Tinfoil Index Feed
     - GET /api/tinfoil/feed
     - Get tinfoil custom index feed endpoint https://blawar.github.io/tinfoil/custom_index/  Args:     request (Request): Fastapi Request object     slug (str, optional): Platform slug. Defaults to \"switch\".  Returns:     TinfoilFeedSchema: Tinfoil feed object schema
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - parameter slug: (query)  (optional, default to "switch")
     - returns: RequestBuilder<TinfoilFeedSchema> 
     */
    open class func tinfoilIndexFeedApiTinfoilFeedGetWithRequestBuilder(slug: String? = nil) -> RequestBuilder<TinfoilFeedSchema> {
        let localVariablePath = "/api/tinfoil/feed"
        let localVariableURLString = rommAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "slug": (wrappedValue: slug?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<TinfoilFeedSchema>.Type = rommAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
