//
// FirmwareAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class FirmwareAPI {

    /**
     Add Firmware
     
     - parameter platformId: (query)  
     - parameter files: (form)  
     - returns: AddFirmwareResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func addFirmwareApiFirmwarePost(platformId: Int, files: [URL]) async throws -> AddFirmwareResponse {
        return try await addFirmwareApiFirmwarePostWithRequestBuilder(platformId: platformId, files: files).execute().body
    }

    /**
     Add Firmware
     - POST /api/firmware
     - Upload firmware files endpoint  Args:     request (Request): Fastapi Request object     platform_slug (str): Slug of the platform where to upload the files     files (list[UploadFile], optional): List of files to upload  Raises:     HTTPException  Returns:     AddFirmwareResponse: Standard message response
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - parameter platformId: (query)  
     - parameter files: (form)  
     - returns: RequestBuilder<AddFirmwareResponse> 
     */
    open class func addFirmwareApiFirmwarePostWithRequestBuilder(platformId: Int, files: [URL]) -> RequestBuilder<AddFirmwareResponse> {
        let localVariablePath = "/api/firmware"
        let localVariableURLString = rommAPI.basePath + localVariablePath
        let localVariableFormParams: [String: Any?] = [
            "files": files.encodeToJSON(),
        ]

        let localVariableNonNullParameters = APIHelper.rejectNil(localVariableFormParams)
        let localVariableParameters = APIHelper.convertBoolToString(localVariableNonNullParameters)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "platform_id": (wrappedValue: platformId.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "multipart/form-data",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AddFirmwareResponse>.Type = rommAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Delete Firmware
     
     - returns: BulkOperationResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func deleteFirmwareApiFirmwareDeletePost() async throws -> BulkOperationResponse {
        return try await deleteFirmwareApiFirmwareDeletePostWithRequestBuilder().execute().body
    }

    /**
     Delete Firmware
     - POST /api/firmware/delete
     - Delete firmware endpoint  Args:     request (Request): Fastapi Request object.         {             \"firmware\": List of firmware IDs to delete         }     delete_from_fs (bool, optional): Flag to delete rom from filesystem. Defaults to False.  Returns:     BulkOperationResponse: Bulk operation response with details
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - returns: RequestBuilder<BulkOperationResponse> 
     */
    open class func deleteFirmwareApiFirmwareDeletePostWithRequestBuilder() -> RequestBuilder<BulkOperationResponse> {
        let localVariablePath = "/api/firmware/delete"
        let localVariableURLString = rommAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<BulkOperationResponse>.Type = rommAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get Firmware
     
     - parameter id: (path)  
     - returns: FirmwareSchema
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getFirmwareApiFirmwareIdGet(id: Int) async throws -> FirmwareSchema {
        return try await getFirmwareApiFirmwareIdGetWithRequestBuilder(id: id).execute().body
    }

    /**
     Get Firmware
     - GET /api/firmware/{id}
     - Get firmware endpoint  Args:     request (Request): Fastapi Request object     id (int): Firmware internal id  Returns:     FirmwareSchema: Firmware stored in the database
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - parameter id: (path)  
     - returns: RequestBuilder<FirmwareSchema> 
     */
    open class func getFirmwareApiFirmwareIdGetWithRequestBuilder(id: Int) -> RequestBuilder<FirmwareSchema> {
        var localVariablePath = "/api/firmware/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = rommAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<FirmwareSchema>.Type = rommAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get Firmware Content
     
     - parameter id: (path)  
     - parameter fileName: (path)  
     - returns: Any
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getFirmwareContentApiFirmwareIdContentFileNameGet(id: Int, fileName: String) async throws -> String {
        return try await getFirmwareContentApiFirmwareIdContentFileNameGetWithRequestBuilder(id: id, fileName: fileName).execute().body
    }

    /**
     Get Firmware Content
     - GET /api/firmware/{id}/content/{file_name}
     - Download firmware endpoint  Args:     request (Request): Fastapi Request object     id (int): Rom internal id     file_name (str): Required due to a bug in emulatorjs  Returns:     FileResponse: Returns the firmware file
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - parameter id: (path)  
     - parameter fileName: (path)  
     - returns: RequestBuilder<String> 
     */
    open class func getFirmwareContentApiFirmwareIdContentFileNameGetWithRequestBuilder(id: Int, fileName: String) -> RequestBuilder<String> {
        var localVariablePath = "/api/firmware/{id}/content/{file_name}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let fileNamePreEscape = "\(APIHelper.mapValueToPathItem(fileName))"
        let fileNamePostEscape = fileNamePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{file_name}", with: fileNamePostEscape, options: .literal, range: nil)
        let localVariableURLString = rommAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<String>.Type = rommAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get Platform Firmware
     
     - parameter platformId: (query)  (optional)
     - returns: [FirmwareSchema]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getPlatformFirmwareApiFirmwareGet(platformId: Int? = nil) async throws -> [FirmwareSchema] {
        return try await getPlatformFirmwareApiFirmwareGetWithRequestBuilder(platformId: platformId).execute().body
    }

    /**
     Get Platform Firmware
     - GET /api/firmware
     - Get firmware endpoint  Args:     request (Request): Fastapi Request object  Returns:     list[FirmwareSchema]: Firmware stored in the database
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - parameter platformId: (query)  (optional)
     - returns: RequestBuilder<[FirmwareSchema]> 
     */
    open class func getPlatformFirmwareApiFirmwareGetWithRequestBuilder(platformId: Int? = nil) -> RequestBuilder<[FirmwareSchema]> {
        let localVariablePath = "/api/firmware"
        let localVariableURLString = rommAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "platform_id": (wrappedValue: platformId?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[FirmwareSchema]>.Type = rommAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Head Firmware Content
     
     - parameter id: (path)  
     - parameter fileName: (path)  
     - returns: Any
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func headFirmwareContentApiFirmwareIdContentFileNameHead(id: Int, fileName: String) async throws -> String {
        return try await headFirmwareContentApiFirmwareIdContentFileNameHeadWithRequestBuilder(id: id, fileName: fileName).execute().body
    }

    /**
     Head Firmware Content
     - HEAD /api/firmware/{id}/content/{file_name}
     - Head firmware content endpoint  Args:     request (Request): Fastapi Request object     id (int): Rom internal id     file_name (str): Required due to a bug in emulatorjs  Returns:     FileResponse: Returns the response with headers
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - parameter id: (path)  
     - parameter fileName: (path)  
     - returns: RequestBuilder<String> 
     */
    open class func headFirmwareContentApiFirmwareIdContentFileNameHeadWithRequestBuilder(id: Int, fileName: String) -> RequestBuilder<String> {
        var localVariablePath = "/api/firmware/{id}/content/{file_name}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let fileNamePreEscape = "\(APIHelper.mapValueToPathItem(fileName))"
        let fileNamePostEscape = fileNamePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{file_name}", with: fileNamePostEscape, options: .literal, range: nil)
        let localVariableURLString = rommAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<String>.Type = rommAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "HEAD", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
