//
// PlatformsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class PlatformsAPI {

    /**
     Add Platform
     
     - parameter bodyAddPlatformApiPlatformsPost: (body)  
     - returns: PlatformSchema
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func addPlatformApiPlatformsPost(bodyAddPlatformApiPlatformsPost: BodyAddPlatformApiPlatformsPost) async throws -> PlatformSchema {
        return try await addPlatformApiPlatformsPostWithRequestBuilder(bodyAddPlatformApiPlatformsPost: bodyAddPlatformApiPlatformsPost).execute().body
    }

    /**
     Add Platform
     - POST /api/platforms
     - Create a platform.
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - parameter bodyAddPlatformApiPlatformsPost: (body)  
     - returns: RequestBuilder<PlatformSchema> 
     */
    open class func addPlatformApiPlatformsPostWithRequestBuilder(bodyAddPlatformApiPlatformsPost: BodyAddPlatformApiPlatformsPost) -> RequestBuilder<PlatformSchema> {
        let localVariablePath = "/api/platforms"
        let localVariableURLString = rommAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: bodyAddPlatformApiPlatformsPost)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<PlatformSchema>.Type = rommAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Delete Platform
     
     - parameter id: (path) Platform id. 
     - returns: Any
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func deletePlatformApiPlatformsIdDelete(id: Int) async throws -> String {
        return try await deletePlatformApiPlatformsIdDeleteWithRequestBuilder(id: id).execute().body
    }

    /**
     Delete Platform
     - DELETE /api/platforms/{id}
     - Delete a platform.
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - parameter id: (path) Platform id. 
     - returns: RequestBuilder<String> 
     */
    open class func deletePlatformApiPlatformsIdDeleteWithRequestBuilder(id: Int) -> RequestBuilder<String> {
        var localVariablePath = "/api/platforms/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = rommAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<String>.Type = rommAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get Platform
     
     - parameter id: (path) Platform id. 
     - returns: PlatformSchema
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getPlatformApiPlatformsIdGet(id: Int) async throws -> PlatformSchema {
        return try await getPlatformApiPlatformsIdGetWithRequestBuilder(id: id).execute().body
    }

    /**
     Get Platform
     - GET /api/platforms/{id}
     - Retrieve a platform by ID.
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - parameter id: (path) Platform id. 
     - returns: RequestBuilder<PlatformSchema> 
     */
    open class func getPlatformApiPlatformsIdGetWithRequestBuilder(id: Int) -> RequestBuilder<PlatformSchema> {
        var localVariablePath = "/api/platforms/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = rommAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<PlatformSchema>.Type = rommAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get Platforms
     
     - returns: [PlatformSchema]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getPlatformsApiPlatformsGet() async throws -> [PlatformSchema] {
        return try await getPlatformsApiPlatformsGetWithRequestBuilder().execute().body
    }

    /**
     Get Platforms
     - GET /api/platforms
     - Retrieve platforms.
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - returns: RequestBuilder<[PlatformSchema]> 
     */
    open class func getPlatformsApiPlatformsGetWithRequestBuilder() -> RequestBuilder<[PlatformSchema]> {
        let localVariablePath = "/api/platforms"
        let localVariableURLString = rommAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[PlatformSchema]>.Type = rommAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get Supported Platforms
     
     - returns: [PlatformSchema]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getSupportedPlatformsApiPlatformsSupportedGet() async throws -> [PlatformSchema] {
        return try await getSupportedPlatformsApiPlatformsSupportedGetWithRequestBuilder().execute().body
    }

    /**
     Get Supported Platforms
     - GET /api/platforms/supported
     - Retrieve the list of supported platforms.
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - returns: RequestBuilder<[PlatformSchema]> 
     */
    open class func getSupportedPlatformsApiPlatformsSupportedGetWithRequestBuilder() -> RequestBuilder<[PlatformSchema]> {
        let localVariablePath = "/api/platforms/supported"
        let localVariableURLString = rommAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[PlatformSchema]>.Type = rommAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Update Platform
     
     - parameter id: (path) Platform id. 
     - parameter bodyUpdatePlatformApiPlatformsIdPut: (body)  (optional)
     - returns: PlatformSchema
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func updatePlatformApiPlatformsIdPut(id: Int, bodyUpdatePlatformApiPlatformsIdPut: BodyUpdatePlatformApiPlatformsIdPut? = nil) async throws -> PlatformSchema {
        return try await updatePlatformApiPlatformsIdPutWithRequestBuilder(id: id, bodyUpdatePlatformApiPlatformsIdPut: bodyUpdatePlatformApiPlatformsIdPut).execute().body
    }

    /**
     Update Platform
     - PUT /api/platforms/{id}
     - Update a platform.
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - parameter id: (path) Platform id. 
     - parameter bodyUpdatePlatformApiPlatformsIdPut: (body)  (optional)
     - returns: RequestBuilder<PlatformSchema> 
     */
    open class func updatePlatformApiPlatformsIdPutWithRequestBuilder(id: Int, bodyUpdatePlatformApiPlatformsIdPut: BodyUpdatePlatformApiPlatformsIdPut? = nil) -> RequestBuilder<PlatformSchema> {
        var localVariablePath = "/api/platforms/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = rommAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: bodyUpdatePlatformApiPlatformsIdPut)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<PlatformSchema>.Type = rommAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
