//
// RawAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class RawAPI {

    /**
     Get Raw Asset
     
     - parameter path: (path)  
     - returns: Any
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getRawAssetApiRawAssetsPathGet(path: String) async throws -> String {
        return try await getRawAssetApiRawAssetsPathGetWithRequestBuilder(path: path).execute().body
    }

    /**
     Get Raw Asset
     - GET /api/raw/assets/{path}
     - Download a single asset file  Args:     request (Request): Fastapi Request object     path (str): Relative path to the asset file  Returns:     FileResponse: Returns a single asset file  Raises:     HTTPException: 404 if asset not found or access denied
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - parameter path: (path)  
     - returns: RequestBuilder<String> 
     */
    open class func getRawAssetApiRawAssetsPathGetWithRequestBuilder(path: String) -> RequestBuilder<String> {
        var localVariablePath = "/api/raw/assets/{path}"
        let pathPreEscape = "\(APIHelper.mapValueToPathItem(path))"
        let pathPostEscape = pathPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{path}", with: pathPostEscape, options: .literal, range: nil)
        let localVariableURLString = rommAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<String>.Type = rommAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Head Raw Asset
     
     - parameter path: (path)  
     - returns: Any
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func headRawAssetApiRawAssetsPathHead(path: String) async throws -> String {
        return try await headRawAssetApiRawAssetsPathHeadWithRequestBuilder(path: path).execute().body
    }

    /**
     Head Raw Asset
     - HEAD /api/raw/assets/{path}
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - parameter path: (path)  
     - returns: RequestBuilder<String> 
     */
    open class func headRawAssetApiRawAssetsPathHeadWithRequestBuilder(path: String) -> RequestBuilder<String> {
        var localVariablePath = "/api/raw/assets/{path}"
        let pathPreEscape = "\(APIHelper.mapValueToPathItem(path))"
        let pathPostEscape = pathPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{path}", with: pathPostEscape, options: .literal, range: nil)
        let localVariableURLString = rommAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<String>.Type = rommAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "HEAD", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
