//
// SavesAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class SavesAPI {

    /**
     Add Save
     
     - parameter romId: (query)  
     - parameter emulator: (query)  (optional)
     - returns: SaveSchema
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func addSaveApiSavesPost(romId: Int, emulator: String? = nil) async throws -> SaveSchema {
        return try await addSaveApiSavesPostWithRequestBuilder(romId: romId, emulator: emulator).execute().body
    }

    /**
     Add Save
     - POST /api/saves
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - parameter romId: (query)  
     - parameter emulator: (query)  (optional)
     - returns: RequestBuilder<SaveSchema> 
     */
    open class func addSaveApiSavesPostWithRequestBuilder(romId: Int, emulator: String? = nil) -> RequestBuilder<SaveSchema> {
        let localVariablePath = "/api/saves"
        let localVariableURLString = rommAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "rom_id": (wrappedValue: romId.encodeToJSON(), isExplode: true),
            "emulator": (wrappedValue: emulator?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SaveSchema>.Type = rommAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Delete Saves
     
     - returns: [Int]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func deleteSavesApiSavesDeletePost() async throws -> [Int] {
        return try await deleteSavesApiSavesDeletePostWithRequestBuilder().execute().body
    }

    /**
     Delete Saves
     - POST /api/saves/delete
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - returns: RequestBuilder<[Int]> 
     */
    open class func deleteSavesApiSavesDeletePostWithRequestBuilder() -> RequestBuilder<[Int]> {
        let localVariablePath = "/api/saves/delete"
        let localVariableURLString = rommAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[Int]>.Type = rommAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get Save
     
     - parameter id: (path)  
     - returns: SaveSchema
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getSaveApiSavesIdGet(id: Int) async throws -> SaveSchema {
        return try await getSaveApiSavesIdGetWithRequestBuilder(id: id).execute().body
    }

    /**
     Get Save
     - GET /api/saves/{id}
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - parameter id: (path)  
     - returns: RequestBuilder<SaveSchema> 
     */
    open class func getSaveApiSavesIdGetWithRequestBuilder(id: Int) -> RequestBuilder<SaveSchema> {
        var localVariablePath = "/api/saves/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = rommAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SaveSchema>.Type = rommAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get Saves
     
     - parameter romId: (query)  (optional)
     - parameter platformId: (query)  (optional)
     - returns: [SaveSchema]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getSavesApiSavesGet(romId: Int? = nil, platformId: Int? = nil) async throws -> [SaveSchema] {
        return try await getSavesApiSavesGetWithRequestBuilder(romId: romId, platformId: platformId).execute().body
    }

    /**
     Get Saves
     - GET /api/saves
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - parameter romId: (query)  (optional)
     - parameter platformId: (query)  (optional)
     - returns: RequestBuilder<[SaveSchema]> 
     */
    open class func getSavesApiSavesGetWithRequestBuilder(romId: Int? = nil, platformId: Int? = nil) -> RequestBuilder<[SaveSchema]> {
        let localVariablePath = "/api/saves"
        let localVariableURLString = rommAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "rom_id": (wrappedValue: romId?.encodeToJSON(), isExplode: true),
            "platform_id": (wrappedValue: platformId?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[SaveSchema]>.Type = rommAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Update Save
     
     - parameter id: (path)  
     - returns: SaveSchema
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func updateSaveApiSavesIdPut(id: Int) async throws -> SaveSchema {
        return try await updateSaveApiSavesIdPutWithRequestBuilder(id: id).execute().body
    }

    /**
     Update Save
     - PUT /api/saves/{id}
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - parameter id: (path)  
     - returns: RequestBuilder<SaveSchema> 
     */
    open class func updateSaveApiSavesIdPutWithRequestBuilder(id: Int) -> RequestBuilder<SaveSchema> {
        var localVariablePath = "/api/saves/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = rommAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SaveSchema>.Type = rommAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
