//
// ScreenshotsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class ScreenshotsAPI {

    /**
     Add Screenshot
     
     - parameter romId: (query)  
     - returns: ScreenshotSchema
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func addScreenshotApiScreenshotsPost(romId: Int) async throws -> ScreenshotSchema {
        return try await addScreenshotApiScreenshotsPostWithRequestBuilder(romId: romId).execute().body
    }

    /**
     Add Screenshot
     - POST /api/screenshots
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - parameter romId: (query)  
     - returns: RequestBuilder<ScreenshotSchema> 
     */
    open class func addScreenshotApiScreenshotsPostWithRequestBuilder(romId: Int) -> RequestBuilder<ScreenshotSchema> {
        let localVariablePath = "/api/screenshots"
        let localVariableURLString = rommAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "rom_id": (wrappedValue: romId.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ScreenshotSchema>.Type = rommAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
