//
// SearchAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class SearchAPI {

    /**
     Search Cover
     
     - parameter searchTerm: (query)  (optional, default to "")
     - returns: [SearchCoverSchema]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func searchCoverApiSearchCoverGet(searchTerm: String? = nil) async throws -> [SearchCoverSchema] {
        return try await searchCoverApiSearchCoverGetWithRequestBuilder(searchTerm: searchTerm).execute().body
    }

    /**
     Search Cover
     - GET /api/search/cover
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - parameter searchTerm: (query)  (optional, default to "")
     - returns: RequestBuilder<[SearchCoverSchema]> 
     */
    open class func searchCoverApiSearchCoverGetWithRequestBuilder(searchTerm: String? = nil) -> RequestBuilder<[SearchCoverSchema]> {
        let localVariablePath = "/api/search/cover"
        let localVariableURLString = rommAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "search_term": (wrappedValue: searchTerm?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[SearchCoverSchema]>.Type = rommAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Search Rom
     
     - parameter romId: (query)  
     - parameter searchTerm: (query)  (optional)
     - parameter searchBy: (query)  (optional, default to "name")
     - returns: [SearchRomSchema]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func searchRomApiSearchRomsGet(romId: Int, searchTerm: String? = nil, searchBy: String? = nil) async throws -> [SearchRomSchema] {
        return try await searchRomApiSearchRomsGetWithRequestBuilder(romId: romId, searchTerm: searchTerm, searchBy: searchBy).execute().body
    }

    /**
     Search Rom
     - GET /api/search/roms
     - Search for rom in metadata providers  Args:     request (Request): FastAPI request     rom_id (int): Rom ID     source (str): Source of the rom     search_term (str, optional): Search term. Defaults to None.     search_by (str, optional): Search by name or ID. Defaults to \"name\".     search_extended (bool, optional): Search extended info. Defaults to False.  Returns:     list[SearchRomSchema]: List of matched roms
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - parameter romId: (query)  
     - parameter searchTerm: (query)  (optional)
     - parameter searchBy: (query)  (optional, default to "name")
     - returns: RequestBuilder<[SearchRomSchema]> 
     */
    open class func searchRomApiSearchRomsGetWithRequestBuilder(romId: Int, searchTerm: String? = nil, searchBy: String? = nil) -> RequestBuilder<[SearchRomSchema]> {
        let localVariablePath = "/api/search/roms"
        let localVariableURLString = rommAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "rom_id": (wrappedValue: romId.encodeToJSON(), isExplode: true),
            "search_term": (wrappedValue: searchTerm?.encodeToJSON(), isExplode: true),
            "search_by": (wrappedValue: searchBy?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[SearchRomSchema]>.Type = rommAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
