//
// StatsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class StatsAPI {

    /**
     Stats
     
     - returns: StatsReturn
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func statsApiStatsGet() async throws -> StatsReturn {
        return try await statsApiStatsGetWithRequestBuilder().execute().body
    }

    /**
     Stats
     - GET /api/stats
     - Endpoint to return the current RomM stats  Returns:     dict: Dictionary with all the stats
     - returns: RequestBuilder<StatsReturn> 
     */
    open class func statsApiStatsGetWithRequestBuilder() -> RequestBuilder<StatsReturn> {
        let localVariablePath = "/api/stats"
        let localVariableURLString = rommAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<StatsReturn>.Type = rommAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
