//
// SystemAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class SystemAPI {

    /**
     Heartbeat
     
     - returns: HeartbeatResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func heartbeatApiHeartbeatGet() async throws -> HeartbeatResponse {
        return try await heartbeatApiHeartbeatGetWithRequestBuilder().execute().body
    }

    /**
     Heartbeat
     - GET /api/heartbeat
     - Endpoint to set the CSRF token in cache and return all the basic RomM config  Returns:     HeartbeatReturn: TypedDict structure with all the defined values in the HeartbeatReturn class.
     - returns: RequestBuilder<HeartbeatResponse> 
     */
    open class func heartbeatApiHeartbeatGetWithRequestBuilder() -> RequestBuilder<HeartbeatResponse> {
        let localVariablePath = "/api/heartbeat"
        let localVariableURLString = rommAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<HeartbeatResponse>.Type = rommAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
