//
// TasksAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class TasksAPI {

    /**
     Get Task By Id
     
     - parameter taskId: (path)  
     - returns: TaskStatusResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getTaskByIdApiTasksTaskIdGet(taskId: String) async throws -> TaskStatusResponse {
        return try await getTaskByIdApiTasksTaskIdGetWithRequestBuilder(taskId: taskId).execute().body
    }

    /**
     Get Task By Id
     - GET /api/tasks/{task_id}
     - Get the status of a task by its job ID.  Args:     request (Request): FastAPI Request object     task_id (str): Job ID of the task to retrieve status for Returns:     TaskStatusResponse: Task status information
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - parameter taskId: (path)  
     - returns: RequestBuilder<TaskStatusResponse> 
     */
    open class func getTaskByIdApiTasksTaskIdGetWithRequestBuilder(taskId: String) -> RequestBuilder<TaskStatusResponse> {
        var localVariablePath = "/api/tasks/{task_id}"
        let taskIdPreEscape = "\(APIHelper.mapValueToPathItem(taskId))"
        let taskIdPostEscape = taskIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{task_id}", with: taskIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = rommAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<TaskStatusResponse>.Type = rommAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     List Tasks
     
     - returns: [String: [TaskInfo]]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func listTasksApiTasksGet() async throws -> [String: [TaskInfo]] {
        return try await listTasksApiTasksGetWithRequestBuilder().execute().body
    }

    /**
     List Tasks
     - GET /api/tasks
     - List all available tasks grouped by task type.  Args:     request (Request): FastAPI Request object Returns:     Dictionary with tasks grouped by their type (scheduled, manual, watcher)
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - returns: RequestBuilder<[String: [TaskInfo]]> 
     */
    open class func listTasksApiTasksGetWithRequestBuilder() -> RequestBuilder<[String: [TaskInfo]]> {
        let localVariablePath = "/api/tasks"
        let localVariableURLString = rommAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[String: [TaskInfo]]>.Type = rommAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Run All Tasks
     
     - returns: [TaskExecutionResponse]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func runAllTasksApiTasksRunPost() async throws -> [TaskExecutionResponse] {
        return try await runAllTasksApiTasksRunPostWithRequestBuilder().execute().body
    }

    /**
     Run All Tasks
     - POST /api/tasks/run
     - Run all runnable tasks endpoint  Args:     request (Request): FastAPI Request object Returns:     TaskExecutionResponse: Task execution response with details
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - returns: RequestBuilder<[TaskExecutionResponse]> 
     */
    open class func runAllTasksApiTasksRunPostWithRequestBuilder() -> RequestBuilder<[TaskExecutionResponse]> {
        let localVariablePath = "/api/tasks/run"
        let localVariableURLString = rommAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[TaskExecutionResponse]>.Type = rommAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Run Single Task
     
     - parameter taskName: (path)  
     - returns: TaskExecutionResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func runSingleTaskApiTasksRunTaskNamePost(taskName: String) async throws -> TaskExecutionResponse {
        return try await runSingleTaskApiTasksRunTaskNamePostWithRequestBuilder(taskName: taskName).execute().body
    }

    /**
     Run Single Task
     - POST /api/tasks/run/{task_name}
     - Run a single task endpoint.  Args:     request (Request): FastAPI Request object     task_name (str): Name of the task to run Returns:     TaskExecutionResponse: Task execution response with details
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - parameter taskName: (path)  
     - returns: RequestBuilder<TaskExecutionResponse> 
     */
    open class func runSingleTaskApiTasksRunTaskNamePostWithRequestBuilder(taskName: String) -> RequestBuilder<TaskExecutionResponse> {
        var localVariablePath = "/api/tasks/run/{task_name}"
        let taskNamePreEscape = "\(APIHelper.mapValueToPathItem(taskName))"
        let taskNamePostEscape = taskNamePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{task_name}", with: taskNamePostEscape, options: .literal, range: nil)
        let localVariableURLString = rommAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<TaskExecutionResponse>.Type = rommAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
