//
// UsersAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class UsersAPI {

    /**
     Add User
     
     - parameter bodyAddUserApiUsersPost: (body)  
     - returns: UserSchema
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func addUserApiUsersPost(bodyAddUserApiUsersPost: BodyAddUserApiUsersPost) async throws -> UserSchema {
        return try await addUserApiUsersPostWithRequestBuilder(bodyAddUserApiUsersPost: bodyAddUserApiUsersPost).execute().body
    }

    /**
     Add User
     - POST /api/users
     - Create user endpoint  Args:     request (Request): Fastapi Requests object     username (str): User username     password (str): User password     email (str): User email     role (str): RomM Role object represented as string  Returns:     UserSchema: Newly created user
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - parameter bodyAddUserApiUsersPost: (body)  
     - returns: RequestBuilder<UserSchema> 
     */
    open class func addUserApiUsersPostWithRequestBuilder(bodyAddUserApiUsersPost: BodyAddUserApiUsersPost) -> RequestBuilder<UserSchema> {
        let localVariablePath = "/api/users"
        let localVariableURLString = rommAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: bodyAddUserApiUsersPost)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<UserSchema>.Type = rommAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Create Invite Link
     
     - parameter role: (query)  
     - returns: InviteLinkSchema
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func createInviteLinkApiUsersInviteLinkPost(role: String) async throws -> InviteLinkSchema {
        return try await createInviteLinkApiUsersInviteLinkPostWithRequestBuilder(role: role).execute().body
    }

    /**
     Create Invite Link
     - POST /api/users/invite-link
     - Create an invite link for a user.  Args:     request (Request): FastAPI Request object     role (str): The role of the user  Returns:     InviteLinkSchema: Invite link
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - parameter role: (query)  
     - returns: RequestBuilder<InviteLinkSchema> 
     */
    open class func createInviteLinkApiUsersInviteLinkPostWithRequestBuilder(role: String) -> RequestBuilder<InviteLinkSchema> {
        let localVariablePath = "/api/users/invite-link"
        let localVariableURLString = rommAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "role": (wrappedValue: role.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<InviteLinkSchema>.Type = rommAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Create User From Invite
     
     - parameter bodyCreateUserFromInviteApiUsersRegisterPost: (body)  
     - returns: UserSchema
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func createUserFromInviteApiUsersRegisterPost(bodyCreateUserFromInviteApiUsersRegisterPost: BodyCreateUserFromInviteApiUsersRegisterPost) async throws -> UserSchema {
        return try await createUserFromInviteApiUsersRegisterPostWithRequestBuilder(bodyCreateUserFromInviteApiUsersRegisterPost: bodyCreateUserFromInviteApiUsersRegisterPost).execute().body
    }

    /**
     Create User From Invite
     - POST /api/users/register
     - Create user endpoint with invite link  Args:     username (str): User username     email (str): User email     password (str): User password     token (str): Invite link token  Returns:     UserSchema: Newly created user
     - parameter bodyCreateUserFromInviteApiUsersRegisterPost: (body)  
     - returns: RequestBuilder<UserSchema> 
     */
    open class func createUserFromInviteApiUsersRegisterPostWithRequestBuilder(bodyCreateUserFromInviteApiUsersRegisterPost: BodyCreateUserFromInviteApiUsersRegisterPost) -> RequestBuilder<UserSchema> {
        let localVariablePath = "/api/users/register"
        let localVariableURLString = rommAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: bodyCreateUserFromInviteApiUsersRegisterPost)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<UserSchema>.Type = rommAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Delete User
     
     - parameter id: (path)  
     - returns: Any
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func deleteUserApiUsersIdDelete(id: Int) async throws -> String {
        return try await deleteUserApiUsersIdDeleteWithRequestBuilder(id: id).execute().body
    }

    /**
     Delete User
     - DELETE /api/users/{id}
     - Delete user endpoint  Args:     request (Request): Fastapi Request object     user_id (int): User internal id  Raises:     HTTPException: User is not found in database     HTTPException: User deleting itself     HTTPException: User is the last admin user
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - parameter id: (path)  
     - returns: RequestBuilder<String> 
     */
    open class func deleteUserApiUsersIdDeleteWithRequestBuilder(id: Int) -> RequestBuilder<String> {
        var localVariablePath = "/api/users/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = rommAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<String>.Type = rommAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get Current User
     
     - returns: UserSchema
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getCurrentUserApiUsersMeGet() async throws -> UserSchema {
        return try await getCurrentUserApiUsersMeGetWithRequestBuilder().execute().body
    }

    /**
     Get Current User
     - GET /api/users/me
     - Get current user endpoint  Args:     request (Request): Fastapi Request object  Returns:     UserSchema | None: Current user
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - returns: RequestBuilder<UserSchema> 
     */
    open class func getCurrentUserApiUsersMeGetWithRequestBuilder() -> RequestBuilder<UserSchema> {
        let localVariablePath = "/api/users/me"
        let localVariableURLString = rommAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<UserSchema>.Type = rommAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get User
     
     - parameter id: (path)  
     - returns: UserSchema
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getUserApiUsersIdGet(id: Int) async throws -> UserSchema {
        return try await getUserApiUsersIdGetWithRequestBuilder(id: id).execute().body
    }

    /**
     Get User
     - GET /api/users/{id}
     - Get user endpoint  Args:     request (Request): Fastapi Request object  Returns:     UserSchem: User stored in the RomM's database
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - parameter id: (path)  
     - returns: RequestBuilder<UserSchema> 
     */
    open class func getUserApiUsersIdGetWithRequestBuilder(id: Int) -> RequestBuilder<UserSchema> {
        var localVariablePath = "/api/users/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = rommAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<UserSchema>.Type = rommAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get Users
     
     - returns: [UserSchema]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getUsersApiUsersGet() async throws -> [UserSchema] {
        return try await getUsersApiUsersGetWithRequestBuilder().execute().body
    }

    /**
     Get Users
     - GET /api/users
     - Get all users endpoint  Args:     request (Request): Fastapi Request object  Returns:     list[UserSchema]: All users stored in the RomM's database
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - returns: RequestBuilder<[UserSchema]> 
     */
    open class func getUsersApiUsersGetWithRequestBuilder() -> RequestBuilder<[UserSchema]> {
        let localVariablePath = "/api/users"
        let localVariableURLString = rommAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[UserSchema]>.Type = rommAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Refresh Retro Achievements
     
     - parameter id: (path)  
     - returns: Any
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func refreshRetroAchievementsApiUsersIdRaRefreshPost(id: Int) async throws -> String {
        return try await refreshRetroAchievementsApiUsersIdRaRefreshPostWithRequestBuilder(id: id).execute().body
    }

    /**
     Refresh Retro Achievements
     - POST /api/users/{id}/ra/refresh
     - Refresh RetroAchievements data for a user.  Args:     request (Request): FastAPI Request object     id (int): User ID  Raises:     HTTPException: User not found or no RetroAchievements username set  Returns:     None: Returns 200 OK status
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - parameter id: (path)  
     - returns: RequestBuilder<String> 
     */
    open class func refreshRetroAchievementsApiUsersIdRaRefreshPostWithRequestBuilder(id: Int) -> RequestBuilder<String> {
        var localVariablePath = "/api/users/{id}/ra/refresh"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = rommAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<String>.Type = rommAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Update User
     
     - parameter id: (path)  
     - parameter username: (form)  (optional)
     - parameter password: (form)  (optional)
     - parameter email: (form)  (optional)
     - parameter role: (form)  (optional)
     - parameter enabled: (form)  (optional)
     - parameter raUsername: (form)  (optional)
     - parameter avatar: (form)  (optional)
     - returns: UserSchema
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func updateUserApiUsersIdPut(id: Int, username: String? = nil, password: String? = nil, email: String? = nil, role: String? = nil, enabled: Bool? = nil, raUsername: String? = nil, avatar: URL? = nil) async throws -> UserSchema {
        return try await updateUserApiUsersIdPutWithRequestBuilder(id: id, username: username, password: password, email: email, role: role, enabled: enabled, raUsername: raUsername, avatar: avatar).execute().body
    }

    /**
     Update User
     - PUT /api/users/{id}
     - Update user endpoint  Args:     request (Request): Fastapi Requests object     user_id (int): User internal id     form_data (Annotated[UserUpdateForm, Depends): Form Data with user updated info  Raises:     HTTPException: User is not found in database     HTTPException: Username already in use by another user  Returns:     UserSchema: Updated user info
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - BASIC:
       - type: http
       - name: HTTPBasic
     - parameter id: (path)  
     - parameter username: (form)  (optional)
     - parameter password: (form)  (optional)
     - parameter email: (form)  (optional)
     - parameter role: (form)  (optional)
     - parameter enabled: (form)  (optional)
     - parameter raUsername: (form)  (optional)
     - parameter avatar: (form)  (optional)
     - returns: RequestBuilder<UserSchema> 
     */
    open class func updateUserApiUsersIdPutWithRequestBuilder(id: Int, username: String? = nil, password: String? = nil, email: String? = nil, role: String? = nil, enabled: Bool? = nil, raUsername: String? = nil, avatar: URL? = nil) -> RequestBuilder<UserSchema> {
        var localVariablePath = "/api/users/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = rommAPI.basePath + localVariablePath
        let localVariableFormParams: [String: Any?] = [
            "username": username?.encodeToJSON(),
            "password": password?.encodeToJSON(),
            "email": email?.encodeToJSON(),
            "role": role?.encodeToJSON(),
            "enabled": enabled?.encodeToJSON(),
            "ra_username": raUsername?.encodeToJSON(),
            "avatar": avatar?.encodeToJSON(),
        ]

        let localVariableNonNullParameters = APIHelper.rejectNil(localVariableFormParams)
        let localVariableParameters = APIHelper.convertBoolToString(localVariableNonNullParameters)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/x-www-form-urlencoded",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<UserSchema>.Type = rommAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
