//
// AddFirmwareResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AddFirmwareResponse: Codable, JSONEncodable, Hashable {

    public var uploaded: Int
    public var firmware: [FirmwareSchema]

    public init(uploaded: Int, firmware: [FirmwareSchema]) {
        self.uploaded = uploaded
        self.firmware = firmware
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case uploaded
        case firmware
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(uploaded, forKey: .uploaded)
        try container.encode(firmware, forKey: .firmware)
    }
}

