//
// BodyDeleteRomsApiRomsDeletePost.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct BodyDeleteRomsApiRomsDeletePost: Codable, JSONEncodable, Hashable {

    /** List of rom ids to delete from database. */
    public var roms: [Int]
    /** List of rom ids to delete from filesystem. */
    public var deleteFromFs: [Int]?

    public init(roms: [Int], deleteFromFs: [Int]? = nil) {
        self.roms = roms
        self.deleteFromFs = deleteFromFs
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case roms
        case deleteFromFs = "delete_from_fs"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(roms, forKey: .roms)
        try container.encodeIfPresent(deleteFromFs, forKey: .deleteFromFs)
    }
}

