//
// BulkOperationResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct BulkOperationResponse: Codable, JSONEncodable, Hashable {

    public var successfulItems: Int
    public var failedItems: Int
    public var errors: [String]

    public init(successfulItems: Int, failedItems: Int, errors: [String]) {
        self.successfulItems = successfulItems
        self.failedItems = failedItems
        self.errors = errors
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case successfulItems = "successful_items"
        case failedItems = "failed_items"
        case errors
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(successfulItems, forKey: .successfulItems)
        try container.encode(failedItems, forKey: .failedItems)
        try container.encode(errors, forKey: .errors)
    }
}

