//
// ConfigResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ConfigResponse: Codable, JSONEncodable, Hashable {

    public var EXCLUDED_PLATFORMS: [String]
    public var EXCLUDED_SINGLE_EXT: [String]
    public var EXCLUDED_SINGLE_FILES: [String]
    public var EXCLUDED_MULTI_FILES: [String]
    public var EXCLUDED_MULTI_PARTS_EXT: [String]
    public var EXCLUDED_MULTI_PARTS_FILES: [String]
    public var PLATFORMS_BINDING: [String: String]
    public var PLATFORMS_VERSIONS: [String: String]

    public init(EXCLUDED_PLATFORMS: [String], EXCLUDED_SINGLE_EXT: [String], EXCLUDED_SINGLE_FILES: [String], EXCLUDED_MULTI_FILES: [String], EXCLUDED_MULTI_PARTS_EXT: [String], EXCLUDED_MULTI_PARTS_FILES: [String], PLATFORMS_BINDING: [String: String], PLATFORMS_VERSIONS: [String: String]) {
        self.EXCLUDED_PLATFORMS = EXCLUDED_PLATFORMS
        self.EXCLUDED_SINGLE_EXT = EXCLUDED_SINGLE_EXT
        self.EXCLUDED_SINGLE_FILES = EXCLUDED_SINGLE_FILES
        self.EXCLUDED_MULTI_FILES = EXCLUDED_MULTI_FILES
        self.EXCLUDED_MULTI_PARTS_EXT = EXCLUDED_MULTI_PARTS_EXT
        self.EXCLUDED_MULTI_PARTS_FILES = EXCLUDED_MULTI_PARTS_FILES
        self.PLATFORMS_BINDING = PLATFORMS_BINDING
        self.PLATFORMS_VERSIONS = PLATFORMS_VERSIONS
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case EXCLUDED_PLATFORMS
        case EXCLUDED_SINGLE_EXT
        case EXCLUDED_SINGLE_FILES
        case EXCLUDED_MULTI_FILES
        case EXCLUDED_MULTI_PARTS_EXT
        case EXCLUDED_MULTI_PARTS_FILES
        case PLATFORMS_BINDING
        case PLATFORMS_VERSIONS
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(EXCLUDED_PLATFORMS, forKey: .EXCLUDED_PLATFORMS)
        try container.encode(EXCLUDED_SINGLE_EXT, forKey: .EXCLUDED_SINGLE_EXT)
        try container.encode(EXCLUDED_SINGLE_FILES, forKey: .EXCLUDED_SINGLE_FILES)
        try container.encode(EXCLUDED_MULTI_FILES, forKey: .EXCLUDED_MULTI_FILES)
        try container.encode(EXCLUDED_MULTI_PARTS_EXT, forKey: .EXCLUDED_MULTI_PARTS_EXT)
        try container.encode(EXCLUDED_MULTI_PARTS_FILES, forKey: .EXCLUDED_MULTI_PARTS_FILES)
        try container.encode(PLATFORMS_BINDING, forKey: .PLATFORMS_BINDING)
        try container.encode(PLATFORMS_VERSIONS, forKey: .PLATFORMS_VERSIONS)
    }
}

