//
// IGDBRelatedGame.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct IGDBRelatedGame: Codable, JSONEncodable, Hashable {

    public var id: Int
    public var name: String
    public var slug: String
    public var type: String
    public var coverUrl: String

    public init(id: Int, name: String, slug: String, type: String, coverUrl: String) {
        self.id = id
        self.name = name
        self.slug = slug
        self.type = type
        self.coverUrl = coverUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case slug
        case type
        case coverUrl = "cover_url"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encode(slug, forKey: .slug)
        try container.encode(type, forKey: .type)
        try container.encode(coverUrl, forKey: .coverUrl)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension IGDBRelatedGame: Identifiable {}
