//
// JobStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** The Status of Job within its lifecycle at any given time. */
public enum JobStatus: String, Codable, CaseIterable {
    case queued = "queued"
    case finished = "finished"
    case failed = "failed"
    case started = "started"
    case deferred = "deferred"
    case scheduled = "scheduled"
    case stopped = "stopped"
    case canceled = "canceled"
}
