//
// PlatformSchema.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PlatformSchema: Codable, JSONEncodable, Hashable {

    public var id: Int
    public var slug: String
    public var fsSlug: String
    public var romCount: Int
    public var name: String
    public var igdbSlug: String?
    public var mobySlug: String?
    public var customName: String?
    public var igdbId: Int?
    public var sgdbId: Int?
    public var mobyId: Int?
    public var launchboxId: Int?
    public var ssId: Int?
    public var raId: Int?
    public var hasheousId: Int?
    public var tgdbId: Int?
    public var category: String?
    public var generation: Int?
    public var familyName: String?
    public var familySlug: String?
    public var url: String?
    public var urlLogo: String?
    public var firmware: [FirmwareSchema]?
    public var aspectRatio: String? = "2 / 3"
    public var createdAt: Date
    public var updatedAt: Date
    public var fsSizeBytes: Int
    public var isUnidentified: Bool
    public var isIdentified: Bool
    public var missingFromFs: Bool
    public var displayName: String

    public init(id: Int, slug: String, fsSlug: String, romCount: Int, name: String, igdbSlug: String?, mobySlug: String?, customName: String? = nil, igdbId: Int? = nil, sgdbId: Int? = nil, mobyId: Int? = nil, launchboxId: Int? = nil, ssId: Int? = nil, raId: Int? = nil, hasheousId: Int? = nil, tgdbId: Int? = nil, category: String? = nil, generation: Int? = nil, familyName: String? = nil, familySlug: String? = nil, url: String? = nil, urlLogo: String? = nil, firmware: [FirmwareSchema]? = nil, aspectRatio: String? = "2 / 3", createdAt: Date, updatedAt: Date, fsSizeBytes: Int, isUnidentified: Bool, isIdentified: Bool, missingFromFs: Bool, displayName: String) {
        self.id = id
        self.slug = slug
        self.fsSlug = fsSlug
        self.romCount = romCount
        self.name = name
        self.igdbSlug = igdbSlug
        self.mobySlug = mobySlug
        self.customName = customName
        self.igdbId = igdbId
        self.sgdbId = sgdbId
        self.mobyId = mobyId
        self.launchboxId = launchboxId
        self.ssId = ssId
        self.raId = raId
        self.hasheousId = hasheousId
        self.tgdbId = tgdbId
        self.category = category
        self.generation = generation
        self.familyName = familyName
        self.familySlug = familySlug
        self.url = url
        self.urlLogo = urlLogo
        self.firmware = firmware
        self.aspectRatio = aspectRatio
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.fsSizeBytes = fsSizeBytes
        self.isUnidentified = isUnidentified
        self.isIdentified = isIdentified
        self.missingFromFs = missingFromFs
        self.displayName = displayName
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case slug
        case fsSlug = "fs_slug"
        case romCount = "rom_count"
        case name
        case igdbSlug = "igdb_slug"
        case mobySlug = "moby_slug"
        case customName = "custom_name"
        case igdbId = "igdb_id"
        case sgdbId = "sgdb_id"
        case mobyId = "moby_id"
        case launchboxId = "launchbox_id"
        case ssId = "ss_id"
        case raId = "ra_id"
        case hasheousId = "hasheous_id"
        case tgdbId = "tgdb_id"
        case category
        case generation
        case familyName = "family_name"
        case familySlug = "family_slug"
        case url
        case urlLogo = "url_logo"
        case firmware
        case aspectRatio = "aspect_ratio"
        case createdAt = "created_at"
        case updatedAt = "updated_at"
        case fsSizeBytes = "fs_size_bytes"
        case isUnidentified = "is_unidentified"
        case isIdentified = "is_identified"
        case missingFromFs = "missing_from_fs"
        case displayName = "display_name"
    }

    // Decodable protocol methods
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        id = try container.decode(Int.self, forKey: .id)
        slug = try container.decode(String.self, forKey: .slug)
        fsSlug = try container.decode(String.self, forKey: .fsSlug)
        romCount = try container.decode(Int.self, forKey: .romCount)
        name = try container.decode(String.self, forKey: .name)
        igdbSlug = try container.decodeIfPresent(String.self, forKey: .igdbSlug)
        mobySlug = try container.decodeIfPresent(String.self, forKey: .mobySlug)
        customName = try container.decodeIfPresent(String.self, forKey: .customName)
        igdbId = try container.decodeIfPresent(Int.self, forKey: .igdbId)
        sgdbId = try container.decodeIfPresent(Int.self, forKey: .sgdbId)
        mobyId = try container.decodeIfPresent(Int.self, forKey: .mobyId)
        launchboxId = try container.decodeIfPresent(Int.self, forKey: .launchboxId)
        ssId = try container.decodeIfPresent(Int.self, forKey: .ssId)
        raId = try container.decodeIfPresent(Int.self, forKey: .raId)
        hasheousId = try container.decodeIfPresent(Int.self, forKey: .hasheousId)
        tgdbId = try container.decodeIfPresent(Int.self, forKey: .tgdbId)
        category = try container.decodeIfPresent(String.self, forKey: .category)
        generation = try container.decodeIfPresent(Int.self, forKey: .generation)
        familyName = try container.decodeIfPresent(String.self, forKey: .familyName)
        familySlug = try container.decodeIfPresent(String.self, forKey: .familySlug)
        url = try container.decodeIfPresent(String.self, forKey: .url)
        urlLogo = try container.decodeIfPresent(String.self, forKey: .urlLogo)
        firmware = try container.decodeIfPresent([FirmwareSchema].self, forKey: .firmware)
        aspectRatio = try container.decodeIfPresent(String.self, forKey: .aspectRatio) ?? "2 / 3"
        
        // Handle flexible Date decoding
        createdAt = try container.decodeFlexibleDate(forKey: .createdAt)
        updatedAt = try container.decodeFlexibleDate(forKey: .updatedAt)
        
        fsSizeBytes = try container.decode(Int.self, forKey: .fsSizeBytes)
        isUnidentified = try container.decode(Bool.self, forKey: .isUnidentified)
        isIdentified = try container.decode(Bool.self, forKey: .isIdentified)
        missingFromFs = try container.decode(Bool.self, forKey: .missingFromFs)
        displayName = try container.decode(String.self, forKey: .displayName)
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(slug, forKey: .slug)
        try container.encode(fsSlug, forKey: .fsSlug)
        try container.encode(romCount, forKey: .romCount)
        try container.encode(name, forKey: .name)
        try container.encode(igdbSlug, forKey: .igdbSlug)
        try container.encode(mobySlug, forKey: .mobySlug)
        try container.encodeIfPresent(customName, forKey: .customName)
        try container.encodeIfPresent(igdbId, forKey: .igdbId)
        try container.encodeIfPresent(sgdbId, forKey: .sgdbId)
        try container.encodeIfPresent(mobyId, forKey: .mobyId)
        try container.encodeIfPresent(launchboxId, forKey: .launchboxId)
        try container.encodeIfPresent(ssId, forKey: .ssId)
        try container.encodeIfPresent(raId, forKey: .raId)
        try container.encodeIfPresent(hasheousId, forKey: .hasheousId)
        try container.encodeIfPresent(tgdbId, forKey: .tgdbId)
        try container.encodeIfPresent(category, forKey: .category)
        try container.encodeIfPresent(generation, forKey: .generation)
        try container.encodeIfPresent(familyName, forKey: .familyName)
        try container.encodeIfPresent(familySlug, forKey: .familySlug)
        try container.encodeIfPresent(url, forKey: .url)
        try container.encodeIfPresent(urlLogo, forKey: .urlLogo)
        try container.encodeIfPresent(firmware, forKey: .firmware)
        try container.encodeIfPresent(aspectRatio, forKey: .aspectRatio)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(updatedAt, forKey: .updatedAt)
        try container.encode(fsSizeBytes, forKey: .fsSizeBytes)
        try container.encode(isUnidentified, forKey: .isUnidentified)
        try container.encode(isIdentified, forKey: .isIdentified)
        try container.encode(missingFromFs, forKey: .missingFromFs)
        try container.encode(displayName, forKey: .displayName)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension PlatformSchema: Identifiable {}
