//
// RomMobyMetadata.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RomMobyMetadata: Codable, JSONEncodable, Hashable {

    public var mobyScore: String?
    public var genres: [String]?
    public var alternateTitles: [String]?
    public var platforms: [MobyMetadataPlatform]?

    public init(mobyScore: String? = nil, genres: [String]? = nil, alternateTitles: [String]? = nil, platforms: [MobyMetadataPlatform]? = nil) {
        self.mobyScore = mobyScore
        self.genres = genres
        self.alternateTitles = alternateTitles
        self.platforms = platforms
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case mobyScore = "moby_score"
        case genres
        case alternateTitles = "alternate_titles"
        case platforms
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(mobyScore, forKey: .mobyScore)
        try container.encodeIfPresent(genres, forKey: .genres)
        try container.encodeIfPresent(alternateTitles, forKey: .alternateTitles)
        try container.encodeIfPresent(platforms, forKey: .platforms)
    }
}

