//
// SearchRomSchema.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SearchRomSchema: Codable, JSONEncodable, Hashable {

    public var id: Int?
    public var igdbId: Int?
    public var mobyId: Int?
    public var ssId: Int?
    public var sgdbId: Int?
    public var platformId: Int
    public var name: String
    public var slug: String? = ""
    public var summary: String? = ""
    public var igdbUrlCover: String? = ""
    public var mobyUrlCover: String? = ""
    public var ssUrlCover: String? = ""
    public var sgdbUrlCover: String? = ""

    public init(id: Int? = nil, igdbId: Int? = nil, mobyId: Int? = nil, ssId: Int? = nil, sgdbId: Int? = nil, platformId: Int, name: String, slug: String? = "", summary: String? = "", igdbUrlCover: String? = "", mobyUrlCover: String? = "", ssUrlCover: String? = "", sgdbUrlCover: String? = "") {
        self.id = id
        self.igdbId = igdbId
        self.mobyId = mobyId
        self.ssId = ssId
        self.sgdbId = sgdbId
        self.platformId = platformId
        self.name = name
        self.slug = slug
        self.summary = summary
        self.igdbUrlCover = igdbUrlCover
        self.mobyUrlCover = mobyUrlCover
        self.ssUrlCover = ssUrlCover
        self.sgdbUrlCover = sgdbUrlCover
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case igdbId = "igdb_id"
        case mobyId = "moby_id"
        case ssId = "ss_id"
        case sgdbId = "sgdb_id"
        case platformId = "platform_id"
        case name
        case slug
        case summary
        case igdbUrlCover = "igdb_url_cover"
        case mobyUrlCover = "moby_url_cover"
        case ssUrlCover = "ss_url_cover"
        case sgdbUrlCover = "sgdb_url_cover"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(igdbId, forKey: .igdbId)
        try container.encodeIfPresent(mobyId, forKey: .mobyId)
        try container.encodeIfPresent(ssId, forKey: .ssId)
        try container.encodeIfPresent(sgdbId, forKey: .sgdbId)
        try container.encode(platformId, forKey: .platformId)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(slug, forKey: .slug)
        try container.encodeIfPresent(summary, forKey: .summary)
        try container.encodeIfPresent(igdbUrlCover, forKey: .igdbUrlCover)
        try container.encodeIfPresent(mobyUrlCover, forKey: .mobyUrlCover)
        try container.encodeIfPresent(ssUrlCover, forKey: .ssUrlCover)
        try container.encodeIfPresent(sgdbUrlCover, forKey: .sgdbUrlCover)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension SearchRomSchema: Identifiable {}
