//
// SearchCoverSchema.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SearchCoverSchema: Codable, JSONEncodable, Hashable {

    public var name: String
    public var resources: [String]

    public init(name: String, resources: [String]) {
        self.name = name
        self.resources = resources
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case resources
    }

    // Decodable protocol methods
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        name = try container.decode(String.self, forKey: .name)
        resources = try container.decode([String].self, forKey: .resources)
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(resources, forKey: .resources)
    }
}

