//
// TaskInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct TaskInfo: Codable, JSONEncodable, Hashable {

    public var name: String
    public var manualRun: Bool
    public var title: String
    public var description: String
    public var enabled: Bool
    public var cronString: String

    public init(name: String, manualRun: Bool, title: String, description: String, enabled: Bool, cronString: String) {
        self.name = name
        self.manualRun = manualRun
        self.title = title
        self.description = description
        self.enabled = enabled
        self.cronString = cronString
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case manualRun = "manual_run"
        case title
        case description
        case enabled
        case cronString = "cron_string"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(manualRun, forKey: .manualRun)
        try container.encode(title, forKey: .title)
        try container.encode(description, forKey: .description)
        try container.encode(enabled, forKey: .enabled)
        try container.encode(cronString, forKey: .cronString)
    }
}

