//
// TaskExecutionResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct TaskExecutionResponse: Codable, JSONEncodable, Hashable {

    public var taskName: String
    public var taskId: String
    public var status: JobStatus?
    public var queuedAt: String

    public init(taskName: String, taskId: String, status: JobStatus?, queuedAt: String) {
        self.taskName = taskName
        self.taskId = taskId
        self.status = status
        self.queuedAt = queuedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case taskName = "task_name"
        case taskId = "task_id"
        case status
        case queuedAt = "queued_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(taskName, forKey: .taskName)
        try container.encode(taskId, forKey: .taskId)
        try container.encode(status, forKey: .status)
        try container.encode(queuedAt, forKey: .queuedAt)
    }
}

