//
// UserSchema.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct UserSchema: Codable, JSONEncodable, Hashable {

    public var id: Int
    public var username: String
    public var email: String?
    public var enabled: Bool
    public var role: Role
    public var oauthScopes: [String]
    public var avatarPath: String
    public var lastLogin: Date?
    public var lastActive: Date?
    public var raUsername: String?
    public var raProgression: RAProgression?
    public var createdAt: Date
    public var updatedAt: Date

    public init(id: Int, username: String, email: String?, enabled: Bool, role: Role, oauthScopes: [String], avatarPath: String, lastLogin: Date?, lastActive: Date?, raUsername: String? = nil, raProgression: RAProgression? = nil, createdAt: Date, updatedAt: Date) {
        self.id = id
        self.username = username
        self.email = email
        self.enabled = enabled
        self.role = role
        self.oauthScopes = oauthScopes
        self.avatarPath = avatarPath
        self.lastLogin = lastLogin
        self.lastActive = lastActive
        self.raUsername = raUsername
        self.raProgression = raProgression
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case username
        case email
        case enabled
        case role
        case oauthScopes = "oauth_scopes"
        case avatarPath = "avatar_path"
        case lastLogin = "last_login"
        case lastActive = "last_active"
        case raUsername = "ra_username"
        case raProgression = "ra_progression"
        case createdAt = "created_at"
        case updatedAt = "updated_at"
    }

    // Decodable protocol methods
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        id = try container.decode(Int.self, forKey: .id)
        username = try container.decode(String.self, forKey: .username)
        email = try container.decodeIfPresent(String.self, forKey: .email)
        enabled = try container.decode(Bool.self, forKey: .enabled)
        role = try container.decode(Role.self, forKey: .role)
        oauthScopes = try container.decode([String].self, forKey: .oauthScopes)
        avatarPath = try container.decode(String.self, forKey: .avatarPath)
        // Handle optional Date fields flexibly
        if container.contains(.lastLogin) {
            lastLogin = try? container.decodeFlexibleDate(forKey: .lastLogin)
        } else {
            lastLogin = nil
        }
        if container.contains(.lastActive) {
            lastActive = try? container.decodeFlexibleDate(forKey: .lastActive)
        } else {
            lastActive = nil
        }
        raUsername = try container.decodeIfPresent(String.self, forKey: .raUsername)
        raProgression = try container.decodeIfPresent(RAProgression.self, forKey: .raProgression)
        createdAt = try container.decodeFlexibleDate(forKey: .createdAt)
        updatedAt = try container.decodeFlexibleDate(forKey: .updatedAt)
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(username, forKey: .username)
        try container.encode(email, forKey: .email)
        try container.encode(enabled, forKey: .enabled)
        try container.encode(role, forKey: .role)
        try container.encode(oauthScopes, forKey: .oauthScopes)
        try container.encode(avatarPath, forKey: .avatarPath)
        try container.encode(lastLogin, forKey: .lastLogin)
        try container.encode(lastActive, forKey: .lastActive)
        try container.encodeIfPresent(raUsername, forKey: .raUsername)
        try container.encodeIfPresent(raProgression, forKey: .raProgression)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(updatedAt, forKey: .updatedAt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension UserSchema: Identifiable {}
