//
// WebrcadeFeedItemSchema.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct WebrcadeFeedItemSchema: Codable, JSONEncodable, Hashable {

    public var title: String
    public var longTitle: String?
    public var description: String?
    public var type: String
    public var thumbnail: String?
    public var background: String?
    public var props: WebrcadeFeedItemPropsSchema

    public init(title: String, longTitle: String? = nil, description: String? = nil, type: String, thumbnail: String? = nil, background: String? = nil, props: WebrcadeFeedItemPropsSchema) {
        self.title = title
        self.longTitle = longTitle
        self.description = description
        self.type = type
        self.thumbnail = thumbnail
        self.background = background
        self.props = props
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case title
        case longTitle
        case description
        case type
        case thumbnail
        case background
        case props
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(title, forKey: .title)
        try container.encodeIfPresent(longTitle, forKey: .longTitle)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encode(type, forKey: .type)
        try container.encodeIfPresent(thumbnail, forKey: .thumbnail)
        try container.encodeIfPresent(background, forKey: .background)
        try container.encode(props, forKey: .props)
    }
}

