name: RommAPI
targets:
  RommAPI:
    type: framework
    platform: iOS
    deploymentTarget: "11.0"
    sources: [RommAPI]
    info:
      path: ./Info.plist
      version: 4.0.1
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    scheme: {}
    dependencies:
    - carthage: AnyCodable
