//
// BodyUpdatePlatformApiPlatformsIdPut.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct BodyUpdatePlatformApiPlatformsIdPut: Codable, JSONEncodable, Hashable {

    public var aspectRatio: String?
    public var customName: String?

    public init(aspectRatio: String? = nil, customName: String? = nil) {
        self.aspectRatio = aspectRatio
        self.customName = customName
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case aspectRatio = "aspect_ratio"
        case customName = "custom_name"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(aspectRatio, forKey: .aspectRatio)
        try container.encodeIfPresent(customName, forKey: .customName)
    }
}

