//
// BodyAddUserApiUsersPost.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct BodyAddUserApiUsersPost: Codable, JSONEncodable, Hashable {

    public var username: String
    public var email: String
    public var password: String
    public var role: String

    public init(username: String, email: String, password: String, role: String) {
        self.username = username
        self.email = email
        self.password = password
        self.role = role
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case username
        case email
        case password
        case role
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(username, forKey: .username)
        try container.encode(email, forKey: .email)
        try container.encode(password, forKey: .password)
        try container.encode(role, forKey: .role)
    }
}

