//
// EarnedAchievement.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct EarnedAchievement: Codable, JSONEncodable, Hashable {

    public var id: String
    public var date: String
    public var dateHardcore: String?

    public init(id: String, date: String, dateHardcore: String? = nil) {
        self.id = id
        self.date = date
        self.dateHardcore = dateHardcore
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case date
        case dateHardcore = "date_hardcore"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(date, forKey: .date)
        try container.encodeIfPresent(dateHardcore, forKey: .dateHardcore)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension EarnedAchievement: Identifiable {}
