//
// EmulationDict.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct EmulationDict: Codable, JSONEncodable, Hashable {

    public var DISABLE_EMULATOR_JS: Bool
    public var DISABLE_RUFFLE_RS: Bool

    public init(DISABLE_EMULATOR_JS: Bool, DISABLE_RUFFLE_RS: Bool) {
        self.DISABLE_EMULATOR_JS = DISABLE_EMULATOR_JS
        self.DISABLE_RUFFLE_RS = DISABLE_RUFFLE_RS
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case DISABLE_EMULATOR_JS
        case DISABLE_RUFFLE_RS
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(DISABLE_EMULATOR_JS, forKey: .DISABLE_EMULATOR_JS)
        try container.encode(DISABLE_RUFFLE_RS, forKey: .DISABLE_RUFFLE_RS)
    }
}

