//
// FrontendDict.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct FrontendDict: Codable, JSONEncodable, Hashable {

    public var UPLOAD_TIMEOUT: Int
    public var DISABLE_USERPASS_LOGIN: Bool
    public var YOUTUBE_BASE_URL: String

    public init(UPLOAD_TIMEOUT: Int, DISABLE_USERPASS_LOGIN: Bool, YOUTUBE_BASE_URL: String) {
        self.UPLOAD_TIMEOUT = UPLOAD_TIMEOUT
        self.DISABLE_USERPASS_LOGIN = DISABLE_USERPASS_LOGIN
        self.YOUTUBE_BASE_URL = YOUTUBE_BASE_URL
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case UPLOAD_TIMEOUT
        case DISABLE_USERPASS_LOGIN
        case YOUTUBE_BASE_URL
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(UPLOAD_TIMEOUT, forKey: .UPLOAD_TIMEOUT)
        try container.encode(DISABLE_USERPASS_LOGIN, forKey: .DISABLE_USERPASS_LOGIN)
        try container.encode(YOUTUBE_BASE_URL, forKey: .YOUTUBE_BASE_URL)
    }
}

