//
// HeartbeatResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct HeartbeatResponse: Codable, JSONEncodable, Hashable {

    public var SYSTEM: SystemDict
    public var METADATA_SOURCES: MetadataSourcesDict
    public var FILESYSTEM: FilesystemDict
    public var EMULATION: EmulationDict
    public var FRONTEND: FrontendDict
    public var OIDC: OIDCDict

    public init(SYSTEM: SystemDict, METADATA_SOURCES: MetadataSourcesDict, FILESYSTEM: FilesystemDict, EMULATION: EmulationDict, FRONTEND: FrontendDict, OIDC: OIDCDict) {
        self.SYSTEM = SYSTEM
        self.METADATA_SOURCES = METADATA_SOURCES
        self.FILESYSTEM = FILESYSTEM
        self.EMULATION = EMULATION
        self.FRONTEND = FRONTEND
        self.OIDC = OIDC
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case SYSTEM
        case METADATA_SOURCES
        case FILESYSTEM
        case EMULATION
        case FRONTEND
        case OIDC
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(SYSTEM, forKey: .SYSTEM)
        try container.encode(METADATA_SOURCES, forKey: .METADATA_SOURCES)
        try container.encode(FILESYSTEM, forKey: .FILESYSTEM)
        try container.encode(EMULATION, forKey: .EMULATION)
        try container.encode(FRONTEND, forKey: .FRONTEND)
        try container.encode(OIDC, forKey: .OIDC)
    }
}

