//
// IGDBAgeRating.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct IGDBAgeRating: Codable, JSONEncodable, Hashable {

    public var rating: String
    public var category: String
    public var ratingCoverUrl: String

    public init(rating: String, category: String, ratingCoverUrl: String) {
        self.rating = rating
        self.category = category
        self.ratingCoverUrl = ratingCoverUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case rating
        case category
        case ratingCoverUrl = "rating_cover_url"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(rating, forKey: .rating)
        try container.encode(category, forKey: .category)
        try container.encode(ratingCoverUrl, forKey: .ratingCoverUrl)
    }
}

