//
// LaunchboxImage.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct LaunchboxImage: Codable, JSONEncodable, Hashable {

    public var url: String
    public var type: String?
    public var region: String?

    public init(url: String, type: String? = nil, region: String? = nil) {
        self.url = url
        self.type = type
        self.region = region
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case url
        case type
        case region
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(url, forKey: .url)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(region, forKey: .region)
    }
}

