//
// PlatformSchema.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PlatformSchema: Codable, JSONEncodable, Hashable {

    public var id: Int
    public var slug: String
    public var fsSlug: String
    public var romCount: Int
    public var name: String
    public var customName: String?
    public var igdbId: Int?
    public var sgdbId: Int?
    public var mobyId: Int?
    public var launchboxId: Int?
    public var ssId: Int?
    public var raId: Int?
    public var hasheousId: Int?
    public var tgdbId: Int?
    public var category: String?
    public var generation: Int?
    public var familyName: String?
    public var familySlug: String?
    public var url: String?
    public var urlLogo: String?
    public var logoPath: String?
    public var firmware: [FirmwareSchema]?
    public var aspectRatio: String? = "2 / 3"
    public var createdAt: Date
    public var updatedAt: Date
    public var fsSizeBytes: Int
    public var isUnidentified: Bool
    public var isIdentified: Bool
    public var missingFromFs: Bool
    public var displayName: String
    public var mobySlug: String?

    public init(id: Int, slug: String, fsSlug: String, romCount: Int, name: String, customName: String? = nil, igdbId: Int? = nil, sgdbId: Int? = nil, mobyId: Int? = nil, launchboxId: Int? = nil, ssId: Int? = nil, raId: Int? = nil, hasheousId: Int? = nil, tgdbId: Int? = nil, category: String? = nil, generation: Int? = nil, familyName: String? = nil, familySlug: String? = nil, url: String? = nil, urlLogo: String? = nil, logoPath: String? = nil, firmware: [FirmwareSchema]? = nil, aspectRatio: String? = "2 / 3", createdAt: Date, updatedAt: Date, fsSizeBytes: Int, isUnidentified: Bool, isIdentified: Bool, missingFromFs: Bool, displayName: String, mobySlug: String?) {
        self.id = id
        self.slug = slug
        self.fsSlug = fsSlug
        self.romCount = romCount
        self.name = name
        self.customName = customName
        self.igdbId = igdbId
        self.sgdbId = sgdbId
        self.mobyId = mobyId
        self.launchboxId = launchboxId
        self.ssId = ssId
        self.raId = raId
        self.hasheousId = hasheousId
        self.tgdbId = tgdbId
        self.category = category
        self.generation = generation
        self.familyName = familyName
        self.familySlug = familySlug
        self.url = url
        self.urlLogo = urlLogo
        self.logoPath = logoPath
        self.firmware = firmware
        self.aspectRatio = aspectRatio
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.fsSizeBytes = fsSizeBytes
        self.isUnidentified = isUnidentified
        self.isIdentified = isIdentified
        self.missingFromFs = missingFromFs
        self.displayName = displayName
        self.mobySlug = mobySlug
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case slug
        case fsSlug = "fs_slug"
        case romCount = "rom_count"
        case name
        case customName = "custom_name"
        case igdbId = "igdb_id"
        case sgdbId = "sgdb_id"
        case mobyId = "moby_id"
        case launchboxId = "launchbox_id"
        case ssId = "ss_id"
        case raId = "ra_id"
        case hasheousId = "hasheous_id"
        case tgdbId = "tgdb_id"
        case category
        case generation
        case familyName = "family_name"
        case familySlug = "family_slug"
        case url
        case urlLogo = "url_logo"
        case logoPath = "logo_path"
        case firmware
        case aspectRatio = "aspect_ratio"
        case createdAt = "created_at"
        case updatedAt = "updated_at"
        case fsSizeBytes = "fs_size_bytes"
        case isUnidentified = "is_unidentified"
        case isIdentified = "is_identified"
        case missingFromFs = "missing_from_fs"
        case displayName = "display_name"
        case mobySlug = "moby_slug"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(slug, forKey: .slug)
        try container.encode(fsSlug, forKey: .fsSlug)
        try container.encode(romCount, forKey: .romCount)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(customName, forKey: .customName)
        try container.encodeIfPresent(igdbId, forKey: .igdbId)
        try container.encodeIfPresent(sgdbId, forKey: .sgdbId)
        try container.encodeIfPresent(mobyId, forKey: .mobyId)
        try container.encodeIfPresent(launchboxId, forKey: .launchboxId)
        try container.encodeIfPresent(ssId, forKey: .ssId)
        try container.encodeIfPresent(raId, forKey: .raId)
        try container.encodeIfPresent(hasheousId, forKey: .hasheousId)
        try container.encodeIfPresent(tgdbId, forKey: .tgdbId)
        try container.encodeIfPresent(category, forKey: .category)
        try container.encodeIfPresent(generation, forKey: .generation)
        try container.encodeIfPresent(familyName, forKey: .familyName)
        try container.encodeIfPresent(familySlug, forKey: .familySlug)
        try container.encodeIfPresent(url, forKey: .url)
        try container.encodeIfPresent(urlLogo, forKey: .urlLogo)
        try container.encodeIfPresent(logoPath, forKey: .logoPath)
        try container.encodeIfPresent(firmware, forKey: .firmware)
        try container.encodeIfPresent(aspectRatio, forKey: .aspectRatio)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(updatedAt, forKey: .updatedAt)
        try container.encode(fsSizeBytes, forKey: .fsSizeBytes)
        try container.encode(isUnidentified, forKey: .isUnidentified)
        try container.encode(isIdentified, forKey: .isIdentified)
        try container.encode(missingFromFs, forKey: .missingFromFs)
        try container.encode(displayName, forKey: .displayName)
        try container.encode(mobySlug, forKey: .mobySlug)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension PlatformSchema: Identifiable {}
