//
// RAGameRomAchievement.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RAGameRomAchievement: Codable, JSONEncodable, Hashable {

    public var raId: Int?
    public var title: String?
    public var description: String?
    public var points: Int?
    public var numAwarded: Int?
    public var numAwardedHardcore: Int?
    public var badgeId: String?
    public var badgeUrlLock: String?
    public var badgePathLock: String?
    public var badgeUrl: String?
    public var badgePath: String?
    public var displayOrder: Int?
    public var type: String?

    public init(raId: Int?, title: String?, description: String?, points: Int?, numAwarded: Int?, numAwardedHardcore: Int?, badgeId: String?, badgeUrlLock: String?, badgePathLock: String?, badgeUrl: String?, badgePath: String?, displayOrder: Int?, type: String?) {
        self.raId = raId
        self.title = title
        self.description = description
        self.points = points
        self.numAwarded = numAwarded
        self.numAwardedHardcore = numAwardedHardcore
        self.badgeId = badgeId
        self.badgeUrlLock = badgeUrlLock
        self.badgePathLock = badgePathLock
        self.badgeUrl = badgeUrl
        self.badgePath = badgePath
        self.displayOrder = displayOrder
        self.type = type
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case raId = "ra_id"
        case title
        case description
        case points
        case numAwarded = "num_awarded"
        case numAwardedHardcore = "num_awarded_hardcore"
        case badgeId = "badge_id"
        case badgeUrlLock = "badge_url_lock"
        case badgePathLock = "badge_path_lock"
        case badgeUrl = "badge_url"
        case badgePath = "badge_path"
        case displayOrder = "display_order"
        case type
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(raId, forKey: .raId)
        try container.encode(title, forKey: .title)
        try container.encode(description, forKey: .description)
        try container.encode(points, forKey: .points)
        try container.encode(numAwarded, forKey: .numAwarded)
        try container.encode(numAwardedHardcore, forKey: .numAwardedHardcore)
        try container.encode(badgeId, forKey: .badgeId)
        try container.encode(badgeUrlLock, forKey: .badgeUrlLock)
        try container.encode(badgePathLock, forKey: .badgePathLock)
        try container.encode(badgeUrl, forKey: .badgeUrl)
        try container.encode(badgePath, forKey: .badgePath)
        try container.encode(displayOrder, forKey: .displayOrder)
        try container.encode(type, forKey: .type)
    }
}

