//
// RAProgression.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RAProgression: Codable, JSONEncodable, Hashable {

    public var total: Int?
    public var results: [RAUserGameProgression]?

    public init(total: Int? = nil, results: [RAUserGameProgression]? = nil) {
        self.total = total
        self.results = results
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case total
        case results
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(total, forKey: .total)
        try container.encodeIfPresent(results, forKey: .results)
    }
}

