//
// RAUserGameProgression.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RAUserGameProgression: Codable, JSONEncodable, Hashable {

    public var romRaId: Int?
    public var maxPossible: Int?
    public var numAwarded: Int?
    public var numAwardedHardcore: Int?
    public var earnedAchievements: [EarnedAchievement]

    public init(romRaId: Int?, maxPossible: Int?, numAwarded: Int?, numAwardedHardcore: Int?, earnedAchievements: [EarnedAchievement]) {
        self.romRaId = romRaId
        self.maxPossible = maxPossible
        self.numAwarded = numAwarded
        self.numAwardedHardcore = numAwardedHardcore
        self.earnedAchievements = earnedAchievements
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case romRaId = "rom_ra_id"
        case maxPossible = "max_possible"
        case numAwarded = "num_awarded"
        case numAwardedHardcore = "num_awarded_hardcore"
        case earnedAchievements = "earned_achievements"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(romRaId, forKey: .romRaId)
        try container.encode(maxPossible, forKey: .maxPossible)
        try container.encode(numAwarded, forKey: .numAwarded)
        try container.encode(numAwardedHardcore, forKey: .numAwardedHardcore)
        try container.encode(earnedAchievements, forKey: .earnedAchievements)
    }
}

