//
// Role.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum Role: String, Codable, CaseIterable {
    case viewer = "viewer"
    case editor = "editor"
    case admin = "admin"
}
