//
// RomFileCategory.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum RomFileCategory: String, Codable, CaseIterable {
    case dlc = "dlc"
    case hack = "hack"
    case manual = "manual"
    case patch = "patch"
    case update = "update"
    case mod = "mod"
    case demo = "demo"
    case translation = "translation"
    case prototype = "prototype"
}
