//
// RomHasheousMetadata.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RomHasheousMetadata: Codable, JSONEncodable, Hashable {

    public var tosecMatch: Bool?
    public var mameArcadeMatch: Bool?
    public var mameMessMatch: Bool?
    public var nointroMatch: Bool?
    public var redumpMatch: Bool?
    public var whdloadMatch: Bool?
    public var raMatch: Bool?
    public var fbneoMatch: Bool?

    public init(tosecMatch: Bool? = nil, mameArcadeMatch: Bool? = nil, mameMessMatch: Bool? = nil, nointroMatch: Bool? = nil, redumpMatch: Bool? = nil, whdloadMatch: Bool? = nil, raMatch: Bool? = nil, fbneoMatch: Bool? = nil) {
        self.tosecMatch = tosecMatch
        self.mameArcadeMatch = mameArcadeMatch
        self.mameMessMatch = mameMessMatch
        self.nointroMatch = nointroMatch
        self.redumpMatch = redumpMatch
        self.whdloadMatch = whdloadMatch
        self.raMatch = raMatch
        self.fbneoMatch = fbneoMatch
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case tosecMatch = "tosec_match"
        case mameArcadeMatch = "mame_arcade_match"
        case mameMessMatch = "mame_mess_match"
        case nointroMatch = "nointro_match"
        case redumpMatch = "redump_match"
        case whdloadMatch = "whdload_match"
        case raMatch = "ra_match"
        case fbneoMatch = "fbneo_match"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(tosecMatch, forKey: .tosecMatch)
        try container.encodeIfPresent(mameArcadeMatch, forKey: .mameArcadeMatch)
        try container.encodeIfPresent(mameMessMatch, forKey: .mameMessMatch)
        try container.encodeIfPresent(nointroMatch, forKey: .nointroMatch)
        try container.encodeIfPresent(redumpMatch, forKey: .redumpMatch)
        try container.encodeIfPresent(whdloadMatch, forKey: .whdloadMatch)
        try container.encodeIfPresent(raMatch, forKey: .raMatch)
        try container.encodeIfPresent(fbneoMatch, forKey: .fbneoMatch)
    }
}

