//
// RomIGDBMetadata.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RomIGDBMetadata: Codable, JSONEncodable, Hashable {

    public var totalRating: String?
    public var aggregatedRating: String?
    public var firstReleaseDate: Int?
    public var youtubeVideoId: String?
    public var genres: [String]?
    public var franchises: [String]?
    public var alternativeNames: [String]?
    public var collections: [String]?
    public var companies: [String]?
    public var gameModes: [String]?
    public var ageRatings: [IGDBAgeRating]?
    public var platforms: [IGDBMetadataPlatform]?
    public var expansions: [IGDBRelatedGame]?
    public var dlcs: [IGDBRelatedGame]?
    public var remasters: [IGDBRelatedGame]?
    public var remakes: [IGDBRelatedGame]?
    public var expandedGames: [IGDBRelatedGame]?
    public var ports: [IGDBRelatedGame]?
    public var similarGames: [IGDBRelatedGame]?

    public init(totalRating: String? = nil, aggregatedRating: String? = nil, firstReleaseDate: Int? = nil, youtubeVideoId: String? = nil, genres: [String]? = nil, franchises: [String]? = nil, alternativeNames: [String]? = nil, collections: [String]? = nil, companies: [String]? = nil, gameModes: [String]? = nil, ageRatings: [IGDBAgeRating]? = nil, platforms: [IGDBMetadataPlatform]? = nil, expansions: [IGDBRelatedGame]? = nil, dlcs: [IGDBRelatedGame]? = nil, remasters: [IGDBRelatedGame]? = nil, remakes: [IGDBRelatedGame]? = nil, expandedGames: [IGDBRelatedGame]? = nil, ports: [IGDBRelatedGame]? = nil, similarGames: [IGDBRelatedGame]? = nil) {
        self.totalRating = totalRating
        self.aggregatedRating = aggregatedRating
        self.firstReleaseDate = firstReleaseDate
        self.youtubeVideoId = youtubeVideoId
        self.genres = genres
        self.franchises = franchises
        self.alternativeNames = alternativeNames
        self.collections = collections
        self.companies = companies
        self.gameModes = gameModes
        self.ageRatings = ageRatings
        self.platforms = platforms
        self.expansions = expansions
        self.dlcs = dlcs
        self.remasters = remasters
        self.remakes = remakes
        self.expandedGames = expandedGames
        self.ports = ports
        self.similarGames = similarGames
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case totalRating = "total_rating"
        case aggregatedRating = "aggregated_rating"
        case firstReleaseDate = "first_release_date"
        case youtubeVideoId = "youtube_video_id"
        case genres
        case franchises
        case alternativeNames = "alternative_names"
        case collections
        case companies
        case gameModes = "game_modes"
        case ageRatings = "age_ratings"
        case platforms
        case expansions
        case dlcs
        case remasters
        case remakes
        case expandedGames = "expanded_games"
        case ports
        case similarGames = "similar_games"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(totalRating, forKey: .totalRating)
        try container.encodeIfPresent(aggregatedRating, forKey: .aggregatedRating)
        try container.encodeIfPresent(firstReleaseDate, forKey: .firstReleaseDate)
        try container.encodeIfPresent(youtubeVideoId, forKey: .youtubeVideoId)
        try container.encodeIfPresent(genres, forKey: .genres)
        try container.encodeIfPresent(franchises, forKey: .franchises)
        try container.encodeIfPresent(alternativeNames, forKey: .alternativeNames)
        try container.encodeIfPresent(collections, forKey: .collections)
        try container.encodeIfPresent(companies, forKey: .companies)
        try container.encodeIfPresent(gameModes, forKey: .gameModes)
        try container.encodeIfPresent(ageRatings, forKey: .ageRatings)
        try container.encodeIfPresent(platforms, forKey: .platforms)
        try container.encodeIfPresent(expansions, forKey: .expansions)
        try container.encodeIfPresent(dlcs, forKey: .dlcs)
        try container.encodeIfPresent(remasters, forKey: .remasters)
        try container.encodeIfPresent(remakes, forKey: .remakes)
        try container.encodeIfPresent(expandedGames, forKey: .expandedGames)
        try container.encodeIfPresent(ports, forKey: .ports)
        try container.encodeIfPresent(similarGames, forKey: .similarGames)
    }
}

