//
// RomLaunchboxMetadata.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RomLaunchboxMetadata: Codable, JSONEncodable, Hashable {

    public var firstReleaseDate: Int?
    public var maxPlayers: Int?
    public var releaseType: String?
    public var cooperative: Bool?
    public var youtubeVideoId: String?
    public var communityRating: Double?
    public var communityRatingCount: Int?
    public var wikipediaUrl: String?
    public var esrb: String?
    public var genres: [String]?
    public var companies: [String]?
    public var images: [LaunchboxImage]?

    public init(firstReleaseDate: Int? = nil, maxPlayers: Int? = nil, releaseType: String? = nil, cooperative: Bool? = nil, youtubeVideoId: String? = nil, communityRating: Double? = nil, communityRatingCount: Int? = nil, wikipediaUrl: String? = nil, esrb: String? = nil, genres: [String]? = nil, companies: [String]? = nil, images: [LaunchboxImage]? = nil) {
        self.firstReleaseDate = firstReleaseDate
        self.maxPlayers = maxPlayers
        self.releaseType = releaseType
        self.cooperative = cooperative
        self.youtubeVideoId = youtubeVideoId
        self.communityRating = communityRating
        self.communityRatingCount = communityRatingCount
        self.wikipediaUrl = wikipediaUrl
        self.esrb = esrb
        self.genres = genres
        self.companies = companies
        self.images = images
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case firstReleaseDate = "first_release_date"
        case maxPlayers = "max_players"
        case releaseType = "release_type"
        case cooperative
        case youtubeVideoId = "youtube_video_id"
        case communityRating = "community_rating"
        case communityRatingCount = "community_rating_count"
        case wikipediaUrl = "wikipedia_url"
        case esrb
        case genres
        case companies
        case images
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(firstReleaseDate, forKey: .firstReleaseDate)
        try container.encodeIfPresent(maxPlayers, forKey: .maxPlayers)
        try container.encodeIfPresent(releaseType, forKey: .releaseType)
        try container.encodeIfPresent(cooperative, forKey: .cooperative)
        try container.encodeIfPresent(youtubeVideoId, forKey: .youtubeVideoId)
        try container.encodeIfPresent(communityRating, forKey: .communityRating)
        try container.encodeIfPresent(communityRatingCount, forKey: .communityRatingCount)
        try container.encodeIfPresent(wikipediaUrl, forKey: .wikipediaUrl)
        try container.encodeIfPresent(esrb, forKey: .esrb)
        try container.encodeIfPresent(genres, forKey: .genres)
        try container.encodeIfPresent(companies, forKey: .companies)
        try container.encodeIfPresent(images, forKey: .images)
    }
}

