//
// RomMetadataSchema.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RomMetadataSchema: Codable, JSONEncodable, Hashable {

    public var romId: Int
    public var genres: [String]
    public var franchises: [String]
    public var collections: [String]
    public var companies: [String]
    public var gameModes: [String]
    public var ageRatings: [String]
    public var firstReleaseDate: Int?
    public var averageRating: Double?

    public init(romId: Int, genres: [String], franchises: [String], collections: [String], companies: [String], gameModes: [String], ageRatings: [String], firstReleaseDate: Int?, averageRating: Double?) {
        self.romId = romId
        self.genres = genres
        self.franchises = franchises
        self.collections = collections
        self.companies = companies
        self.gameModes = gameModes
        self.ageRatings = ageRatings
        self.firstReleaseDate = firstReleaseDate
        self.averageRating = averageRating
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case romId = "rom_id"
        case genres
        case franchises
        case collections
        case companies
        case gameModes = "game_modes"
        case ageRatings = "age_ratings"
        case firstReleaseDate = "first_release_date"
        case averageRating = "average_rating"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(romId, forKey: .romId)
        try container.encode(genres, forKey: .genres)
        try container.encode(franchises, forKey: .franchises)
        try container.encode(collections, forKey: .collections)
        try container.encode(companies, forKey: .companies)
        try container.encode(gameModes, forKey: .gameModes)
        try container.encode(ageRatings, forKey: .ageRatings)
        try container.encode(firstReleaseDate, forKey: .firstReleaseDate)
        try container.encode(averageRating, forKey: .averageRating)
    }
}

