//
// RomRAMetadata.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RomRAMetadata: Codable, JSONEncodable, Hashable {

    public var firstReleaseDate: Int?
    public var genres: [String]?
    public var companies: [String]?
    public var achievements: [RAGameRomAchievement]?

    public init(firstReleaseDate: Int? = nil, genres: [String]? = nil, companies: [String]? = nil, achievements: [RAGameRomAchievement]? = nil) {
        self.firstReleaseDate = firstReleaseDate
        self.genres = genres
        self.companies = companies
        self.achievements = achievements
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case firstReleaseDate = "first_release_date"
        case genres
        case companies
        case achievements
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(firstReleaseDate, forKey: .firstReleaseDate)
        try container.encodeIfPresent(genres, forKey: .genres)
        try container.encodeIfPresent(companies, forKey: .companies)
        try container.encodeIfPresent(achievements, forKey: .achievements)
    }
}

