//
// RomSSMetadata.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RomSSMetadata: Codable, JSONEncodable, Hashable {

    public var ssScore: String?
    public var firstReleaseDate: Int?
    public var alternativeNames: [String]?
    public var companies: [String]?
    public var franchises: [String]?
    public var gameModes: [String]?
    public var genres: [String]?

    public init(ssScore: String? = nil, firstReleaseDate: Int? = nil, alternativeNames: [String]? = nil, companies: [String]? = nil, franchises: [String]? = nil, gameModes: [String]? = nil, genres: [String]? = nil) {
        self.ssScore = ssScore
        self.firstReleaseDate = firstReleaseDate
        self.alternativeNames = alternativeNames
        self.companies = companies
        self.franchises = franchises
        self.gameModes = gameModes
        self.genres = genres
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case ssScore = "ss_score"
        case firstReleaseDate = "first_release_date"
        case alternativeNames = "alternative_names"
        case companies
        case franchises
        case gameModes = "game_modes"
        case genres
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(ssScore, forKey: .ssScore)
        try container.encodeIfPresent(firstReleaseDate, forKey: .firstReleaseDate)
        try container.encodeIfPresent(alternativeNames, forKey: .alternativeNames)
        try container.encodeIfPresent(companies, forKey: .companies)
        try container.encodeIfPresent(franchises, forKey: .franchises)
        try container.encodeIfPresent(gameModes, forKey: .gameModes)
        try container.encodeIfPresent(genres, forKey: .genres)
    }
}

