//
// RomUserSchema.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RomUserSchema: Codable, JSONEncodable, Hashable {

    public var id: Int
    public var userId: Int
    public var romId: Int
    public var createdAt: Date
    public var updatedAt: Date
    public var lastPlayed: Date?
    public var noteRawMarkdown: String
    public var noteIsPublic: Bool
    public var isMainSibling: Bool
    public var backlogged: Bool
    public var nowPlaying: Bool
    public var hidden: Bool
    public var rating: Int
    public var difficulty: Int
    public var completion: Int
    public var status: RomUserStatus?
    public var userUsername: String

    public init(id: Int, userId: Int, romId: Int, createdAt: Date, updatedAt: Date, lastPlayed: Date?, noteRawMarkdown: String, noteIsPublic: Bool, isMainSibling: Bool, backlogged: Bool, nowPlaying: Bool, hidden: Bool, rating: Int, difficulty: Int, completion: Int, status: RomUserStatus?, userUsername: String) {
        self.id = id
        self.userId = userId
        self.romId = romId
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.lastPlayed = lastPlayed
        self.noteRawMarkdown = noteRawMarkdown
        self.noteIsPublic = noteIsPublic
        self.isMainSibling = isMainSibling
        self.backlogged = backlogged
        self.nowPlaying = nowPlaying
        self.hidden = hidden
        self.rating = rating
        self.difficulty = difficulty
        self.completion = completion
        self.status = status
        self.userUsername = userUsername
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case userId = "user_id"
        case romId = "rom_id"
        case createdAt = "created_at"
        case updatedAt = "updated_at"
        case lastPlayed = "last_played"
        case noteRawMarkdown = "note_raw_markdown"
        case noteIsPublic = "note_is_public"
        case isMainSibling = "is_main_sibling"
        case backlogged
        case nowPlaying = "now_playing"
        case hidden
        case rating
        case difficulty
        case completion
        case status
        case userUsername = "user__username"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(userId, forKey: .userId)
        try container.encode(romId, forKey: .romId)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(updatedAt, forKey: .updatedAt)
        try container.encode(lastPlayed, forKey: .lastPlayed)
        try container.encode(noteRawMarkdown, forKey: .noteRawMarkdown)
        try container.encode(noteIsPublic, forKey: .noteIsPublic)
        try container.encode(isMainSibling, forKey: .isMainSibling)
        try container.encode(backlogged, forKey: .backlogged)
        try container.encode(nowPlaying, forKey: .nowPlaying)
        try container.encode(hidden, forKey: .hidden)
        try container.encode(rating, forKey: .rating)
        try container.encode(difficulty, forKey: .difficulty)
        try container.encode(completion, forKey: .completion)
        try container.encode(status, forKey: .status)
        try container.encode(userUsername, forKey: .userUsername)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension RomUserSchema: Identifiable {}
