//
// RomUserStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum RomUserStatus: String, Codable, CaseIterable {
    case incomplete = "incomplete"
    case finished = "finished"
    case completed100 = "completed_100"
    case retired = "retired"
    case neverPlaying = "never_playing"
}
