//
// SearchCoverSchema.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SearchCoverSchema: Codable, JSONEncodable, Hashable {

    public var name: String
    public var resources: [AnyCodable]

    public init(name: String, resources: [AnyCodable]) {
        self.name = name
        self.resources = resources
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case resources
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(resources, forKey: .resources)
    }
}

