//
// StatsReturn.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct StatsReturn: Codable, JSONEncodable, Hashable {

    public var PLATFORMS: Int
    public var ROMS: Int
    public var SAVES: Int
    public var STATES: Int
    public var SCREENSHOTS: Int
    public var TOTAL_FILESIZE_BYTES: Int

    public init(PLATFORMS: Int, ROMS: Int, SAVES: Int, STATES: Int, SCREENSHOTS: Int, TOTAL_FILESIZE_BYTES: Int) {
        self.PLATFORMS = PLATFORMS
        self.ROMS = ROMS
        self.SAVES = SAVES
        self.STATES = STATES
        self.SCREENSHOTS = SCREENSHOTS
        self.TOTAL_FILESIZE_BYTES = TOTAL_FILESIZE_BYTES
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case PLATFORMS
        case ROMS
        case SAVES
        case STATES
        case SCREENSHOTS
        case TOTAL_FILESIZE_BYTES
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(PLATFORMS, forKey: .PLATFORMS)
        try container.encode(ROMS, forKey: .ROMS)
        try container.encode(SAVES, forKey: .SAVES)
        try container.encode(STATES, forKey: .STATES)
        try container.encode(SCREENSHOTS, forKey: .SCREENSHOTS)
        try container.encode(TOTAL_FILESIZE_BYTES, forKey: .TOTAL_FILESIZE_BYTES)
    }
}

