//
// TinfoilFeedSchema.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TinfoilFeedSchema: Codable, JSONEncodable, Hashable {

    public var files: [TinfoilFeedFileSchema]
    public var directories: [String]
    public var titledb: [String: TinfoilFeedTitleDBSchema]?
    public var success: String?
    public var error: String?

    public init(files: [TinfoilFeedFileSchema], directories: [String], titledb: [String: TinfoilFeedTitleDBSchema]? = nil, success: String? = nil, error: String? = nil) {
        self.files = files
        self.directories = directories
        self.titledb = titledb
        self.success = success
        self.error = error
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case files
        case directories
        case titledb
        case success
        case error
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(files, forKey: .files)
        try container.encode(directories, forKey: .directories)
        try container.encodeIfPresent(titledb, forKey: .titledb)
        try container.encodeIfPresent(success, forKey: .success)
        try container.encodeIfPresent(error, forKey: .error)
    }
}

