//
// UserSchema.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UserSchema: Codable, JSONEncodable, Hashable {

    public var id: Int
    public var username: String
    public var email: String?
    public var enabled: Bool
    public var role: Role
    public var oauthScopes: [String]
    public var avatarPath: String
    public var lastLogin: Date?
    public var lastActive: Date?
    public var raUsername: String?
    public var raProgression: RAProgression?
    public var createdAt: Date
    public var updatedAt: Date

    public init(id: Int, username: String, email: String?, enabled: Bool, role: Role, oauthScopes: [String], avatarPath: String, lastLogin: Date?, lastActive: Date?, raUsername: String? = nil, raProgression: RAProgression? = nil, createdAt: Date, updatedAt: Date) {
        self.id = id
        self.username = username
        self.email = email
        self.enabled = enabled
        self.role = role
        self.oauthScopes = oauthScopes
        self.avatarPath = avatarPath
        self.lastLogin = lastLogin
        self.lastActive = lastActive
        self.raUsername = raUsername
        self.raProgression = raProgression
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case username
        case email
        case enabled
        case role
        case oauthScopes = "oauth_scopes"
        case avatarPath = "avatar_path"
        case lastLogin = "last_login"
        case lastActive = "last_active"
        case raUsername = "ra_username"
        case raProgression = "ra_progression"
        case createdAt = "created_at"
        case updatedAt = "updated_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(username, forKey: .username)
        try container.encode(email, forKey: .email)
        try container.encode(enabled, forKey: .enabled)
        try container.encode(role, forKey: .role)
        try container.encode(oauthScopes, forKey: .oauthScopes)
        try container.encode(avatarPath, forKey: .avatarPath)
        try container.encode(lastLogin, forKey: .lastLogin)
        try container.encode(lastActive, forKey: .lastActive)
        try container.encodeIfPresent(raUsername, forKey: .raUsername)
        try container.encodeIfPresent(raProgression, forKey: .raProgression)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(updatedAt, forKey: .updatedAt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension UserSchema: Identifiable {}
