//
// VirtualCollectionSchema.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct VirtualCollectionSchema: Codable, JSONEncodable, Hashable {

    public static let romIdsRule = ArrayRule(minItems: nil, maxItems: nil, uniqueItems: true)
    public var name: String
    public var description: String
    public var romIds: Set<Int>
    public var romCount: Int
    public var pathCoverSmall: String?
    public var pathCoverLarge: String?
    public var pathCoversSmall: [String]
    public var pathCoversLarge: [String]
    public var id: String
    public var type: String
    public var isPublic: Bool? = true
    public var isFavorite: Bool? = false
    public var isVirtual: Bool? = true
    public var createdAt: Date
    public var updatedAt: Date

    public init(name: String, description: String, romIds: Set<Int>, romCount: Int, pathCoverSmall: String?, pathCoverLarge: String?, pathCoversSmall: [String], pathCoversLarge: [String], id: String, type: String, isPublic: Bool? = true, isFavorite: Bool? = false, isVirtual: Bool? = true, createdAt: Date, updatedAt: Date) {
        self.name = name
        self.description = description
        self.romIds = romIds
        self.romCount = romCount
        self.pathCoverSmall = pathCoverSmall
        self.pathCoverLarge = pathCoverLarge
        self.pathCoversSmall = pathCoversSmall
        self.pathCoversLarge = pathCoversLarge
        self.id = id
        self.type = type
        self.isPublic = isPublic
        self.isFavorite = isFavorite
        self.isVirtual = isVirtual
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case description
        case romIds = "rom_ids"
        case romCount = "rom_count"
        case pathCoverSmall = "path_cover_small"
        case pathCoverLarge = "path_cover_large"
        case pathCoversSmall = "path_covers_small"
        case pathCoversLarge = "path_covers_large"
        case id
        case type
        case isPublic = "is_public"
        case isFavorite = "is_favorite"
        case isVirtual = "is_virtual"
        case createdAt = "created_at"
        case updatedAt = "updated_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(description, forKey: .description)
        try container.encode(romIds, forKey: .romIds)
        try container.encode(romCount, forKey: .romCount)
        try container.encode(pathCoverSmall, forKey: .pathCoverSmall)
        try container.encode(pathCoverLarge, forKey: .pathCoverLarge)
        try container.encode(pathCoversSmall, forKey: .pathCoversSmall)
        try container.encode(pathCoversLarge, forKey: .pathCoversLarge)
        try container.encode(id, forKey: .id)
        try container.encode(type, forKey: .type)
        try container.encodeIfPresent(isPublic, forKey: .isPublic)
        try container.encodeIfPresent(isFavorite, forKey: .isFavorite)
        try container.encodeIfPresent(isVirtual, forKey: .isVirtual)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(updatedAt, forKey: .updatedAt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension VirtualCollectionSchema: Identifiable {}
