//
// WebrcadeFeedSchema.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct WebrcadeFeedSchema: Codable, JSONEncodable, Hashable {

    public var title: String
    public var longTitle: String?
    public var description: String?
    public var thumbnail: String?
    public var background: String?
    public var categories: [WebrcadeFeedCategorySchema]

    public init(title: String, longTitle: String? = nil, description: String? = nil, thumbnail: String? = nil, background: String? = nil, categories: [WebrcadeFeedCategorySchema]) {
        self.title = title
        self.longTitle = longTitle
        self.description = description
        self.thumbnail = thumbnail
        self.background = background
        self.categories = categories
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case title
        case longTitle
        case description
        case thumbnail
        case background
        case categories
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(title, forKey: .title)
        try container.encodeIfPresent(longTitle, forKey: .longTitle)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(thumbnail, forKey: .thumbnail)
        try container.encodeIfPresent(background, forKey: .background)
        try container.encode(categories, forKey: .categories)
    }
}

